/*
 * Created on 28 oct 2015 ( Time 21:40:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.sun.resorts.holidays.model.PuestoDeTrabajo;
import org.sun.resorts.holidays.model.jpa.PuestoDeTrabajoEntity;
import java.util.List;
import org.sun.resorts.holidays.business.service.PuestoDeTrabajoService;
import org.sun.resorts.holidays.business.service.mapping.PuestoDeTrabajoServiceMapper;
import org.sun.resorts.holidays.data.repository.jpa.PuestoDeTrabajoJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of PuestoDeTrabajoService
 */
@Component
@Transactional
public class PuestoDeTrabajoServiceImpl implements PuestoDeTrabajoService {

	@Resource
	private PuestoDeTrabajoJpaRepository puestoDeTrabajoJpaRepository;

	@Resource
	private PuestoDeTrabajoServiceMapper puestoDeTrabajoServiceMapper;
	
	
	public PuestoDeTrabajo findById(Integer idpuestoDeTrabajo) {
		PuestoDeTrabajoEntity puestoDeTrabajoEntity = puestoDeTrabajoJpaRepository.findOne(idpuestoDeTrabajo);
		return puestoDeTrabajoServiceMapper.mapPuestoDeTrabajoEntityToPuestoDeTrabajo(puestoDeTrabajoEntity);
	}

	
	public List<PuestoDeTrabajo> findAll() {
		Iterable<PuestoDeTrabajoEntity> entities = puestoDeTrabajoJpaRepository.findAll();
		List<PuestoDeTrabajo> beans = new ArrayList<PuestoDeTrabajo>();
		for(PuestoDeTrabajoEntity puestoDeTrabajoEntity : entities) {
			beans.add(puestoDeTrabajoServiceMapper.mapPuestoDeTrabajoEntityToPuestoDeTrabajo(puestoDeTrabajoEntity));
		}
		return beans;
	}

	
	public PuestoDeTrabajo save(PuestoDeTrabajo puestoDeTrabajo) {
		return update(puestoDeTrabajo) ;
	}

	
	public PuestoDeTrabajo create(PuestoDeTrabajo puestoDeTrabajo) {
		PuestoDeTrabajoEntity puestoDeTrabajoEntity = puestoDeTrabajoJpaRepository.findOne(puestoDeTrabajo.getIdpuestoDeTrabajo());
		if( puestoDeTrabajoEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		puestoDeTrabajoEntity = new PuestoDeTrabajoEntity();
		puestoDeTrabajoServiceMapper.mapPuestoDeTrabajoToPuestoDeTrabajoEntity(puestoDeTrabajo, puestoDeTrabajoEntity);
		PuestoDeTrabajoEntity puestoDeTrabajoEntitySaved = puestoDeTrabajoJpaRepository.save(puestoDeTrabajoEntity);
		return puestoDeTrabajoServiceMapper.mapPuestoDeTrabajoEntityToPuestoDeTrabajo(puestoDeTrabajoEntitySaved);
	}

	
	public PuestoDeTrabajo update(PuestoDeTrabajo puestoDeTrabajo) {
		PuestoDeTrabajoEntity puestoDeTrabajoEntity = puestoDeTrabajoJpaRepository.findOne(puestoDeTrabajo.getIdpuestoDeTrabajo());
		puestoDeTrabajoServiceMapper.mapPuestoDeTrabajoToPuestoDeTrabajoEntity(puestoDeTrabajo, puestoDeTrabajoEntity);
		PuestoDeTrabajoEntity puestoDeTrabajoEntitySaved = puestoDeTrabajoJpaRepository.save(puestoDeTrabajoEntity);
		return puestoDeTrabajoServiceMapper.mapPuestoDeTrabajoEntityToPuestoDeTrabajo(puestoDeTrabajoEntitySaved);
	}

	
	public void delete(Integer idpuestoDeTrabajo) {
		puestoDeTrabajoJpaRepository.delete(idpuestoDeTrabajo);
	}

	public PuestoDeTrabajoJpaRepository getPuestoDeTrabajoJpaRepository() {
		return puestoDeTrabajoJpaRepository;
	}

	public void setPuestoDeTrabajoJpaRepository(PuestoDeTrabajoJpaRepository puestoDeTrabajoJpaRepository) {
		this.puestoDeTrabajoJpaRepository = puestoDeTrabajoJpaRepository;
	}

	public PuestoDeTrabajoServiceMapper getPuestoDeTrabajoServiceMapper() {
		return puestoDeTrabajoServiceMapper;
	}

	public void setPuestoDeTrabajoServiceMapper(PuestoDeTrabajoServiceMapper puestoDeTrabajoServiceMapper) {
		this.puestoDeTrabajoServiceMapper = puestoDeTrabajoServiceMapper;
	}

}
