/*
 * Created on 17 oct 2015 ( Time 10:46:16 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.sun.resorts.holidays.data.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "horario"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="horario")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="HorarioEntity.countAll", query="SELECT COUNT(x) FROM HorarioEntity x" )
} )
public class HorarioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idHORARIO", nullable=false)
    private Integer    idhorario    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIME)
    @Column(name="HORA_INICIO", nullable=false)
    private Date       horaInicio   ;

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_FIN", nullable=false)
    private Date       horaFin      ;

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_INICIO_ESPECIAL")
    private Date       horaInicioEspecial ;

    @Temporal(TemporalType.TIME)
    @Column(name="HORA_FIN_ESPECIAL")
    private Date       horaFinEspecial ;

	// "idPuestoTrabajo" (column "ID_PUESTO_TRABAJO") is not defined by itself because used as FK in a link 
	// "idTurnoTrabajo" (column "ID_TURNO_TRABAJO") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumns({    
  	  @JoinColumn(name = "ID_TURNO_TRABAJO", referencedColumnName = "idTURNOS_DE_TRABAJO"),
  	  @JoinColumn(name = "ID_PUESTO_TRABAJO_AS", referencedColumnName = "ID_PUESTO_TRABAJO")
  	})
    private TurnosDeTrabajoEntity turnosDeTrabajo;

    @ManyToOne
    @JoinColumn(name="ID_PUESTO_TRABAJO", referencedColumnName="idPUESTO_DE_TRABAJO")
    private PuestoDeTrabajoEntity puestoDeTrabajo;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public HorarioEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdhorario( Integer idhorario ) {
        this.idhorario = idhorario ;
    }
    public Integer getIdhorario() {
        return this.idhorario;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : HORA_INICIO ( TIME ) 
    public void setHoraInicio( Date horaInicio ) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }

    //--- DATABASE MAPPING : HORA_FIN ( TIME ) 
    public void setHoraFin( Date horaFin ) {
        this.horaFin = horaFin;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }

    //--- DATABASE MAPPING : HORA_INICIO_ESPECIAL ( TIME ) 
    public void setHoraInicioEspecial( Date horaInicioEspecial ) {
        this.horaInicioEspecial = horaInicioEspecial;
    }
    public Date getHoraInicioEspecial() {
        return this.horaInicioEspecial;
    }

    //--- DATABASE MAPPING : HORA_FIN_ESPECIAL ( TIME ) 
    public void setHoraFinEspecial( Date horaFinEspecial ) {
        this.horaFinEspecial = horaFinEspecial;
    }
    public Date getHoraFinEspecial() {
        return this.horaFinEspecial;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTurnosDeTrabajo( TurnosDeTrabajoEntity turnosDeTrabajo ) {
        this.turnosDeTrabajo = turnosDeTrabajo;
    }
    public TurnosDeTrabajoEntity getTurnosDeTrabajo() {
        return this.turnosDeTrabajo;
    }

    public void setPuestoDeTrabajo( PuestoDeTrabajoEntity puestoDeTrabajo ) {
        this.puestoDeTrabajo = puestoDeTrabajo;
    }
    public PuestoDeTrabajoEntity getPuestoDeTrabajo() {
        return this.puestoDeTrabajo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idhorario);
        sb.append("]:"); 
        sb.append(horaInicio);
        sb.append("|");
        sb.append(horaFin);
        sb.append("|");
        sb.append(horaInicioEspecial);
        sb.append("|");
        sb.append(horaFinEspecial);
        return sb.toString(); 
    } 

}
