/*
 * Created on 28 oct 2015 ( Time 21:40:09 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.DetallePlanilla;
import org.sun.resorts.holidays.model.jpa.DetallePlanillaEntity;
import org.sun.resorts.holidays.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class DetallePlanillaServiceMapperTest {

	private DetallePlanillaServiceMapper detallePlanillaServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		detallePlanillaServiceMapper = new DetallePlanillaServiceMapper();
		detallePlanillaServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'DetallePlanillaEntity' to 'DetallePlanilla'
	 * @param detallePlanillaEntity
	 */
	@Test
	public void testMapDetallePlanillaEntityToDetallePlanilla() {
		// Given
		DetallePlanillaEntity detallePlanillaEntity = new DetallePlanillaEntity();
		detallePlanillaEntity.setFechaInicio(mockValues.nextDate());
		detallePlanillaEntity.setFechaFin(mockValues.nextDate());
		detallePlanillaEntity.setObservaciones(mockValues.nextString(50));
		
		// When
		DetallePlanilla detallePlanilla = detallePlanillaServiceMapper.mapDetallePlanillaEntityToDetallePlanilla(detallePlanillaEntity);
		
		// Then
		assertEquals(detallePlanillaEntity.getFechaInicio(), detallePlanilla.getFechaInicio());
		assertEquals(detallePlanillaEntity.getFechaFin(), detallePlanilla.getFechaFin());
		assertEquals(detallePlanillaEntity.getObservaciones(), detallePlanilla.getObservaciones());
	}
	
	/**
	 * Test : Mapping from 'DetallePlanilla' to 'DetallePlanillaEntity'
	 */
	@Test
	public void testMapDetallePlanillaToDetallePlanillaEntity() {
		// Given
		DetallePlanilla detallePlanilla = new DetallePlanilla();
		detallePlanilla.setFechaInicio(mockValues.nextDate());
		detallePlanilla.setFechaFin(mockValues.nextDate());
		detallePlanilla.setObservaciones(mockValues.nextString(50));

		DetallePlanillaEntity detallePlanillaEntity = new DetallePlanillaEntity();
		
		// When
		detallePlanillaServiceMapper.mapDetallePlanillaToDetallePlanillaEntity(detallePlanilla, detallePlanillaEntity);
		
		// Then
		assertEquals(detallePlanilla.getFechaInicio(), detallePlanillaEntity.getFechaInicio());
		assertEquals(detallePlanilla.getFechaFin(), detallePlanillaEntity.getFechaFin());
		assertEquals(detallePlanilla.getObservaciones(), detallePlanillaEntity.getObservaciones());
	}

}