/*
 * Created on 28 oct 2015 ( Time 21:40:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.PlanillasHasEmpleados;
import org.sun.resorts.holidays.model.jpa.PlanillasHasEmpleadosEntity;
import org.sun.resorts.holidays.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PlanillasHasEmpleadosServiceMapperTest {

	private PlanillasHasEmpleadosServiceMapper planillasHasEmpleadosServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		planillasHasEmpleadosServiceMapper = new PlanillasHasEmpleadosServiceMapper();
		planillasHasEmpleadosServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PlanillasHasEmpleadosEntity' to 'PlanillasHasEmpleados'
	 * @param planillasHasEmpleadosEntity
	 */
	@Test
	public void testMapPlanillasHasEmpleadosEntityToPlanillasHasEmpleados() {
		// Given
		PlanillasHasEmpleadosEntity planillasHasEmpleadosEntity = new PlanillasHasEmpleadosEntity();
		
		// When
		PlanillasHasEmpleados planillasHasEmpleados = planillasHasEmpleadosServiceMapper.mapPlanillasHasEmpleadosEntityToPlanillasHasEmpleados(planillasHasEmpleadosEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'PlanillasHasEmpleados' to 'PlanillasHasEmpleadosEntity'
	 */
	@Test
	public void testMapPlanillasHasEmpleadosToPlanillasHasEmpleadosEntity() {
		// Given
		PlanillasHasEmpleados planillasHasEmpleados = new PlanillasHasEmpleados();

		PlanillasHasEmpleadosEntity planillasHasEmpleadosEntity = new PlanillasHasEmpleadosEntity();
		
		// When
		planillasHasEmpleadosServiceMapper.mapPlanillasHasEmpleadosToPlanillasHasEmpleadosEntity(planillasHasEmpleados, planillasHasEmpleadosEntity);
		
		// Then
	}

}