/*
 * Created on 28 oct 2015 ( Time 21:40:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.Horario;
import org.sun.resorts.holidays.model.jpa.HorarioEntity;
import org.sun.resorts.holidays.model.jpa.PuestoDeTrabajoEntity;
import org.sun.resorts.holidays.model.jpa.TurnosDeTrabajoEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class HorarioServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public HorarioServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'HorarioEntity' to 'Horario'
	 * @param horarioEntity
	 */
	public Horario mapHorarioEntityToHorario(HorarioEntity horarioEntity) {
		if(horarioEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Horario horario = map(horarioEntity, Horario.class);

		//--- Link mapping ( link to PuestoDeTrabajo )
		if(horarioEntity.getPuestoDeTrabajo() != null) {
			horario.setIdPuestoTrabajo(horarioEntity.getPuestoDeTrabajo().getIdpuestoDeTrabajo());
		}
		//--- Link mapping ( link to TurnosDeTrabajo )
		if(horarioEntity.getTurnosDeTrabajo() != null) {
			horario.setIdTurnoTrabajo(horarioEntity.getTurnosDeTrabajo().getIdturnosDeTrabajo());
		}
		return horario;
	}
	
	/**
	 * Mapping from 'Horario' to 'HorarioEntity'
	 * @param horario
	 * @param horarioEntity
	 */
	public void mapHorarioToHorarioEntity(Horario horario, HorarioEntity horarioEntity) {
		if(horario == null) {
			return;
		}

		//--- Generic mapping 
		map(horario, horarioEntity);

		//--- Link mapping ( link : horario )
		if( hasLinkToPuestoDeTrabajo(horario) ) {
			PuestoDeTrabajoEntity puestoDeTrabajo1 = new PuestoDeTrabajoEntity();
			puestoDeTrabajo1.setIdpuestoDeTrabajo( horario.getIdPuestoTrabajo() );
			horarioEntity.setPuestoDeTrabajo( puestoDeTrabajo1 );
		} else {
			horarioEntity.setPuestoDeTrabajo( null );
		}

		//--- Link mapping ( link : horario )
		if( hasLinkToTurnosDeTrabajo(horario) ) {
			TurnosDeTrabajoEntity turnosDeTrabajo2 = new TurnosDeTrabajoEntity();
			turnosDeTrabajo2.setIdturnosDeTrabajo( horario.getIdTurnoTrabajo() );
			horarioEntity.setTurnosDeTrabajo( turnosDeTrabajo2 );
		} else {
			horarioEntity.setTurnosDeTrabajo( null );
		}

	}
	
	/**
	 * Verify that PuestoDeTrabajo id is valid.
	 * @param PuestoDeTrabajo PuestoDeTrabajo
	 * @return boolean
	 */
	private boolean hasLinkToPuestoDeTrabajo(Horario horario) {
		if(horario.getIdPuestoTrabajo() != null) {
			return true;
		}
		return false;
	}

	/**
	 * Verify that TurnosDeTrabajo id is valid.
	 * @param TurnosDeTrabajo TurnosDeTrabajo
	 * @return boolean
	 */
	private boolean hasLinkToTurnosDeTrabajo(Horario horario) {
		if(horario.getIdTurnoTrabajo() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}