/*
 * Created on 28 oct 2015 ( Time 21:40:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.TurnosTrabajoEspeciales;
import org.sun.resorts.holidays.model.jpa.TurnosTrabajoEspecialesEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TurnosTrabajoEspecialesServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TurnosTrabajoEspecialesServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TurnosTrabajoEspecialesEntity' to 'TurnosTrabajoEspeciales'
	 * @param turnosTrabajoEspecialesEntity
	 */
	public TurnosTrabajoEspeciales mapTurnosTrabajoEspecialesEntityToTurnosTrabajoEspeciales(TurnosTrabajoEspecialesEntity turnosTrabajoEspecialesEntity) {
		if(turnosTrabajoEspecialesEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TurnosTrabajoEspeciales turnosTrabajoEspeciales = map(turnosTrabajoEspecialesEntity, TurnosTrabajoEspeciales.class);

		return turnosTrabajoEspeciales;
	}
	
	/**
	 * Mapping from 'TurnosTrabajoEspeciales' to 'TurnosTrabajoEspecialesEntity'
	 * @param turnosTrabajoEspeciales
	 * @param turnosTrabajoEspecialesEntity
	 */
	public void mapTurnosTrabajoEspecialesToTurnosTrabajoEspecialesEntity(TurnosTrabajoEspeciales turnosTrabajoEspeciales, TurnosTrabajoEspecialesEntity turnosTrabajoEspecialesEntity) {
		if(turnosTrabajoEspeciales == null) {
			return;
		}

		//--- Generic mapping 
		map(turnosTrabajoEspeciales, turnosTrabajoEspecialesEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}