/*
 * Created on 31 oct 2015 ( Time 10:51:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.sun.resorts.holidays.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "empleados"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="empleados", catalog="sunholidayresortsbbdd" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EmpleadosEntity.countAll", query="SELECT COUNT(x) FROM EmpleadosEntity x" )
} )
public class EmpleadosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idEMPLEADOS", nullable=false)
    private Integer    idempleados  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOMBRE", nullable=false, length=45)
    private String     nombre       ;

    @Column(name="APELLIDO1", length=50)
    private String     apellido1    ;

    @Column(name="APELLIDO2", length=50)
    private String     apellido2    ;

    @Column(name="TELEFONO_MOVIL", nullable=false, length=45)
    private String     telefonoMovil ;

    @Column(name="TELEFONO_FIJO", length=45)
    private String     telefonoFijo ;

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_NACIMIENTO", nullable=false)
    private Date       fechaNacimiento ;

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INCORPORACION", nullable=false)
    private Date       fechaIncorporacion ;

    @Column(name="DNI", nullable=false, length=9)
    private String     dni          ;

    @Column(name="NUM_DIAS_VACACIONES", nullable=false)
    private Integer    numDiasVacaciones ;

    @Column(name="EMAIL", nullable=false, length=45)
    private String     email        ;

    @Column(name="NUM_DIAS_FESTIVOS_PENDIENTES", nullable=false)
    private Integer    numDiasFestivosPendientes ;

	// "idDireccion" (column "ID_DIRECCION") is not defined by itself because used as FK in a link 
	// "perfilesIdperfiles" (column "PERFILES_idPERFILES") is not defined by itself because used as FK in a link 
	// "idTurnoTrabajo" (column "ID_TURNO_TRABAJO") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne(mappedBy="administrador", targetEntity=CentrosDeTrabajoEntity.class)
    private CentrosDeTrabajoEntity administrador;

    @OneToOne(cascade = { CascadeType.PERSIST, CascadeType.REMOVE }, optional = true)
    @JoinColumn(name="ID_DIRECCION", referencedColumnName="idDIRECCION")
    private DireccionEntity direccion   ;

    @OneToMany(mappedBy="empleados", targetEntity=VacacionesEntity.class)
    private List<VacacionesEntity> listOfVacaciones;

    @OneToMany(mappedBy="empleados", targetEntity=UsuariosEntity.class)
    private List<UsuariosEntity> listOfUsuarios;

    @ManyToOne
    @JoinColumn(name="ID_TURNO_TRABAJO", referencedColumnName="idTURNOS_DE_TRABAJO")
    private TurnosDeTrabajoEntity turnosDeTrabajo;

    @OneToOne(mappedBy="coordinador", targetEntity=PuestoDeTrabajoEntity.class)
    private PuestoDeTrabajoEntity listOfPuestoDeTrabajo;

    @ManyToMany(mappedBy="listOfEmpleados", targetEntity=DetallePlanillaEntity.class)
    private List<DetallePlanillaEntity> listOfDetallePlanilla;

    @ManyToOne
    @JoinColumn(name="PERFILES_idPERFILES", referencedColumnName="idPERFILES")
    private PerfilesEntity perfiles    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EmpleadosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdempleados( Integer idempleados ) {
        this.idempleados = idempleados ;
    }
    public Integer getIdempleados() {
        return this.idempleados;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOMBRE ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : APELLIDO1 ( VARCHAR ) 
    public void setApellido1( String apellido1 ) {
        this.apellido1 = apellido1;
    }
    public String getApellido1() {
        return this.apellido1;
    }

    //--- DATABASE MAPPING : APELLIDO2 ( VARCHAR ) 
    public void setApellido2( String apellido2 ) {
        this.apellido2 = apellido2;
    }
    public String getApellido2() {
        return this.apellido2;
    }

    //--- DATABASE MAPPING : TELEFONO_MOVIL ( VARCHAR ) 
    public void setTelefonoMovil( String telefonoMovil ) {
        this.telefonoMovil = telefonoMovil;
    }
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }

    //--- DATABASE MAPPING : TELEFONO_FIJO ( VARCHAR ) 
    public void setTelefonoFijo( String telefonoFijo ) {
        this.telefonoFijo = telefonoFijo;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }

    //--- DATABASE MAPPING : FECHA_NACIMIENTO ( DATE ) 
    public void setFechaNacimiento( Date fechaNacimiento ) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    //--- DATABASE MAPPING : FECHA_INCORPORACION ( DATE ) 
    public void setFechaIncorporacion( Date fechaIncorporacion ) {
        this.fechaIncorporacion = fechaIncorporacion;
    }
    public Date getFechaIncorporacion() {
        return this.fechaIncorporacion;
    }

    //--- DATABASE MAPPING : DNI ( VARCHAR ) 
    public void setDni( String dni ) {
        this.dni = dni;
    }
    public String getDni() {
        return this.dni;
    }

    //--- DATABASE MAPPING : NUM_DIAS_VACACIONES ( INT ) 
    public void setNumDiasVacaciones( Integer numDiasVacaciones ) {
        this.numDiasVacaciones = numDiasVacaciones;
    }
    public Integer getNumDiasVacaciones() {
        return this.numDiasVacaciones;
    }

    //--- DATABASE MAPPING : EMAIL ( VARCHAR ) 
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    //--- DATABASE MAPPING : NUM_DIAS_FESTIVOS_PENDIENTES ( INT ) 
    public void setNumDiasFestivosPendientes( Integer numDiasFestivosPendientes ) {
        this.numDiasFestivosPendientes = numDiasFestivosPendientes;
    }
    public Integer getNumDiasFestivosPendientes() {
        return this.numDiasFestivosPendientes;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setAdministrador( CentrosDeTrabajoEntity administrador ) {
        this.administrador = administrador;
    }
    public CentrosDeTrabajoEntity getAdministrador() {
        return this.administrador;
    }

    public void setDireccion( DireccionEntity direccion ) {
        this.direccion = direccion;
    }
    public DireccionEntity getDireccion() {
        return this.direccion;
    }

    public void setListOfVacaciones( List<VacacionesEntity> listOfVacaciones ) {
        this.listOfVacaciones = listOfVacaciones;
    }
    public List<VacacionesEntity> getListOfVacaciones() {
        return this.listOfVacaciones;
    }

    public void setListOfUsuarios( List<UsuariosEntity> listOfUsuarios ) {
        this.listOfUsuarios = listOfUsuarios;
    }
    public List<UsuariosEntity> getListOfUsuarios() {
        return this.listOfUsuarios;
    }

    public void setTurnosDeTrabajo( TurnosDeTrabajoEntity turnosDeTrabajo ) {
        this.turnosDeTrabajo = turnosDeTrabajo;
    }
    public TurnosDeTrabajoEntity getTurnosDeTrabajo() {
        return this.turnosDeTrabajo;
    }

    public void setListOfPuestoDeTrabajo( PuestoDeTrabajoEntity listOfPuestoDeTrabajo ) {
        this.listOfPuestoDeTrabajo = listOfPuestoDeTrabajo;
    }
    public PuestoDeTrabajoEntity getListOfPuestoDeTrabajo() {
        return this.listOfPuestoDeTrabajo;
    }

    public void setListOfDetallePlanilla( List<DetallePlanillaEntity> listOfDetallePlanilla ) {
        this.listOfDetallePlanilla = listOfDetallePlanilla;
    }
    public List<DetallePlanillaEntity> getListOfDetallePlanilla() {
        return this.listOfDetallePlanilla;
    }

    public void setPerfiles( PerfilesEntity perfiles ) {
        this.perfiles = perfiles;
    }
    public PerfilesEntity getPerfiles() {
        return this.perfiles;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idempleados);
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(apellido1);
        sb.append("|");
        sb.append(apellido2);
        sb.append("|");
        sb.append(telefonoMovil);
        sb.append("|");
        sb.append(telefonoFijo);
        sb.append("|");
        sb.append(fechaNacimiento);
        sb.append("|");
        sb.append(fechaIncorporacion);
        sb.append("|");
        sb.append(dni);
        sb.append("|");
        sb.append(numDiasVacaciones);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(numDiasFestivosPendientes);
        return sb.toString(); 
    } 

}
