/*
 * Created on 31 oct 2015 ( Time 10:51:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.sun.resorts.holidays.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "turnos_de_trabajo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="turnos_de_trabajo", catalog="sunholidayresortsbbdd" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TurnosDeTrabajoEntity.countAll", query="SELECT COUNT(x) FROM TurnosDeTrabajoEntity x" )
} )
public class TurnosDeTrabajoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idTURNOS_DE_TRABAJO", nullable=false)
    private Integer    idturnosDeTrabajo ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOMBRE", nullable=false, length=45)
    private String     nombre       ;

    @Column(name="DESCRIPCION", length=65)
    private String     descripcion  ;

    @Column(name="TURNO_ROTATORIO")
    private Boolean    turnoRotatorio ;

	// "idPuestoTrabajo" (column "ID_PUESTO_TRABAJO") is not defined by itself because used as FK in a link 
	// "idSiguienteTurno" (column "ID_SIGUIENTE_TURNO") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="ID_PUESTO_TRABAJO", referencedColumnName="idPUESTO_DE_TRABAJO")
    private PuestoDeTrabajoEntity puestoDeTrabajo;

    @OneToMany(mappedBy="turnosDeTrabajo", targetEntity=EmpleadosEntity.class)
    private List<EmpleadosEntity> listOfEmpleados;

    @OneToMany(mappedBy="turnosDeTrabajo", targetEntity=TurnosDeTrabajoEntity.class)
    private List<TurnosDeTrabajoEntity> listOfTurnosDeTrabajo;

    @ManyToMany(mappedBy="listOfTurnosDeTrabajo", targetEntity=DetallePlanillaEntity.class)
    private List<DetallePlanillaEntity> listOfDetallePlanilla;

    @OneToOne(mappedBy="turnosDeTrabajo", targetEntity=HorarioEntity.class)
    private HorarioEntity listOfHorario;

    @ManyToOne
    @JoinColumn(name="ID_SIGUIENTE_TURNO", referencedColumnName="idTURNOS_DE_TRABAJO")
    private TurnosDeTrabajoEntity turnosDeTrabajo;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TurnosDeTrabajoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdturnosDeTrabajo( Integer idturnosDeTrabajo ) {
        this.idturnosDeTrabajo = idturnosDeTrabajo ;
    }
    public Integer getIdturnosDeTrabajo() {
        return this.idturnosDeTrabajo;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOMBRE ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : DESCRIPCION ( VARCHAR ) 
    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    //--- DATABASE MAPPING : TURNO_ROTATORIO ( BIT ) 
    public void setTurnoRotatorio( Boolean turnoRotatorio ) {
        this.turnoRotatorio = turnoRotatorio;
    }
    public Boolean getTurnoRotatorio() {
        return this.turnoRotatorio;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPuestoDeTrabajo( PuestoDeTrabajoEntity puestoDeTrabajo ) {
        this.puestoDeTrabajo = puestoDeTrabajo;
    }
    public PuestoDeTrabajoEntity getPuestoDeTrabajo() {
        return this.puestoDeTrabajo;
    }

    public void setListOfEmpleados( List<EmpleadosEntity> listOfEmpleados ) {
        this.listOfEmpleados = listOfEmpleados;
    }
    public List<EmpleadosEntity> getListOfEmpleados() {
        return this.listOfEmpleados;
    }

    public void setListOfTurnosDeTrabajo( List<TurnosDeTrabajoEntity> listOfTurnosDeTrabajo ) {
        this.listOfTurnosDeTrabajo = listOfTurnosDeTrabajo;
    }
    public List<TurnosDeTrabajoEntity> getListOfTurnosDeTrabajo() {
        return this.listOfTurnosDeTrabajo;
    }

    public void setListOfDetallePlanilla( List<DetallePlanillaEntity> listOfDetallePlanilla ) {
        this.listOfDetallePlanilla = listOfDetallePlanilla;
    }
    public List<DetallePlanillaEntity> getListOfDetallePlanilla() {
        return this.listOfDetallePlanilla;
    }

    public void setListOfHorario( HorarioEntity listOfHorario ) {
        this.listOfHorario = listOfHorario;
    }
    public HorarioEntity getListOfHorario() {
        return this.listOfHorario;
    }

    public void setTurnosDeTrabajo( TurnosDeTrabajoEntity turnosDeTrabajo ) {
        this.turnosDeTrabajo = turnosDeTrabajo;
    }
    public TurnosDeTrabajoEntity getTurnosDeTrabajo() {
        return this.turnosDeTrabajo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idturnosDeTrabajo);
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(turnoRotatorio);
        return sb.toString(); 
    } 

}
