/*
 * Created on 31 oct 2015 ( Time 10:51:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.model.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "TurnosDeTrabajoHasDetallePlanillaEntity" ( stored in table "turnos_de_trabajo_has_detalle_planilla" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class TurnosDeTrabajoHasDetallePlanillaEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="TURNOS_DE_TRABAJO_idTURNOS_DE_TRABAJO", nullable=false)
    private Integer    turnosDeTrabajoIdturnosDeTrabajo ;
    
    @Column(name="DETALLE_PLANILLA_ID_DETALLE", nullable=false)
    private Integer    detallePlanillaIdDetalle ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public TurnosDeTrabajoHasDetallePlanillaEntityKey() {
        super();
    }

    public TurnosDeTrabajoHasDetallePlanillaEntityKey( Integer turnosDeTrabajoIdturnosDeTrabajo, Integer detallePlanillaIdDetalle ) {
        super();
        this.turnosDeTrabajoIdturnosDeTrabajo = turnosDeTrabajoIdturnosDeTrabajo ;
        this.detallePlanillaIdDetalle = detallePlanillaIdDetalle ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setTurnosDeTrabajoIdturnosDeTrabajo( Integer value ) {
        this.turnosDeTrabajoIdturnosDeTrabajo = value;
    }
    public Integer getTurnosDeTrabajoIdturnosDeTrabajo() {
        return this.turnosDeTrabajoIdturnosDeTrabajo;
    }

    public void setDetallePlanillaIdDetalle( Integer value ) {
        this.detallePlanillaIdDetalle = value;
    }
    public Integer getDetallePlanillaIdDetalle() {
        return this.detallePlanillaIdDetalle;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		TurnosDeTrabajoHasDetallePlanillaEntityKey other = (TurnosDeTrabajoHasDetallePlanillaEntityKey) obj; 
		//--- Attribute turnosDeTrabajoIdturnosDeTrabajo
		if ( turnosDeTrabajoIdturnosDeTrabajo == null ) { 
			if ( other.turnosDeTrabajoIdturnosDeTrabajo != null ) 
				return false ; 
		} else if ( ! turnosDeTrabajoIdturnosDeTrabajo.equals(other.turnosDeTrabajoIdturnosDeTrabajo) ) 
			return false ; 
		//--- Attribute detallePlanillaIdDetalle
		if ( detallePlanillaIdDetalle == null ) { 
			if ( other.detallePlanillaIdDetalle != null ) 
				return false ; 
		} else if ( ! detallePlanillaIdDetalle.equals(other.detallePlanillaIdDetalle) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute turnosDeTrabajoIdturnosDeTrabajo
		result = prime * result + ((turnosDeTrabajoIdturnosDeTrabajo == null) ? 0 : turnosDeTrabajoIdturnosDeTrabajo.hashCode() ) ; 
		//--- Attribute detallePlanillaIdDetalle
		result = prime * result + ((detallePlanillaIdDetalle == null) ? 0 : detallePlanillaIdDetalle.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(turnosDeTrabajoIdturnosDeTrabajo); 
		sb.append("|"); 
		sb.append(detallePlanillaIdDetalle); 
        return sb.toString();
    }
}
