/*
 * Created on 31 oct 2015 ( Time 10:51:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  


package org.sun.resorts.holidays.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "turnos_de_trabajo_has_detalle_planilla"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="turnos_de_trabajo_has_detalle_planilla", catalog="sunholidayresortsbbdd" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TurnosDeTrabajoHasDetallePlanillaEntity.countAll", query="SELECT COUNT(x) FROM TurnosDeTrabajoHasDetallePlanillaEntity x" )
} )
public class TurnosDeTrabajoHasDetallePlanillaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private TurnosDeTrabajoHasDetallePlanillaEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TurnosDeTrabajoHasDetallePlanillaEntity() {
		super();
		this.compositePrimaryKey = new TurnosDeTrabajoHasDetallePlanillaEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setTurnosDeTrabajoIdturnosDeTrabajo( Integer turnosDeTrabajoIdturnosDeTrabajo ) {
        this.compositePrimaryKey.setTurnosDeTrabajoIdturnosDeTrabajo( turnosDeTrabajoIdturnosDeTrabajo ) ;
    }
    public Integer getTurnosDeTrabajoIdturnosDeTrabajo() {
        return this.compositePrimaryKey.getTurnosDeTrabajoIdturnosDeTrabajo() ;
    }
    public void setDetallePlanillaIdDetalle( Integer detallePlanillaIdDetalle ) {
        this.compositePrimaryKey.setDetallePlanillaIdDetalle( detallePlanillaIdDetalle ) ;
    }
    public Integer getDetallePlanillaIdDetalle() {
        return this.compositePrimaryKey.getDetallePlanillaIdDetalle() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
