/*
 * Created on 17 oct 2015 ( Time 10:46:15 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.sun.resorts.holidays.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "detalle_planilla"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="detalle_planilla")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DetallePlanillaEntity.countAll", query="SELECT COUNT(x) FROM DetallePlanillaEntity x" )
} )
public class DetallePlanillaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idDETALLE_PLANILLA", nullable=false)
    private Integer    iddetallePlanilla ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIO", nullable=false)
    private Date       fechaInicio  ;

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FIN", nullable=false)
    private Date       fechaFin     ;

    @Column(name="OBSERVACIONES", length=50)
    private String     observaciones ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne(mappedBy="detallePlanilla", targetEntity=PlanillasEntity.class)
    private PlanillasEntity listOfPlanillas;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DetallePlanillaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIddetallePlanilla( Integer iddetallePlanilla ) {
        this.iddetallePlanilla = iddetallePlanilla ;
    }
    public Integer getIddetallePlanilla() {
        return this.iddetallePlanilla;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FECHA_INICIO ( DATE ) 
    public void setFechaInicio( Date fechaInicio ) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    //--- DATABASE MAPPING : FECHA_FIN ( DATE ) 
    public void setFechaFin( Date fechaFin ) {
        this.fechaFin = fechaFin;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }

    //--- DATABASE MAPPING : OBSERVACIONES ( VARCHAR ) 
    public void setObservaciones( String observaciones ) {
        this.observaciones = observaciones;
    }
    public String getObservaciones() {
        return this.observaciones;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfPlanillas( PlanillasEntity listOfPlanillas ) {
        this.listOfPlanillas = listOfPlanillas;
    }
    public PlanillasEntity getListOfPlanillas() {
        return this.listOfPlanillas;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(iddetallePlanilla);
        sb.append("]:"); 
        sb.append(fechaInicio);
        sb.append("|");
        sb.append(fechaFin);
        sb.append("|");
        sb.append(observaciones);
        return sb.toString(); 
    } 

}
