/*
 * Created on 17 oct 2015 ( Time 10:46:16 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  


package org.sun.resorts.holidays.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "planillas"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="planillas" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PlanillasEntity.countAll", query="SELECT COUNT(x) FROM PlanillasEntity x" )
} )
public class PlanillasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private PlanillasEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="OBSERVACIONES", length=50)
    private String     observaciones ;

	// "idDetalle" (column "ID_DETALLE") is not defined by itself because used as FK in a link 
	// "idEstado" (column "ID_ESTADO") is not defined by itself because used as FK in a link 
	// "idTipoFecha" (column "ID_TIPO_FECHA") is not defined by itself because used as FK in a link 
	// "idVolumenEspecial" (column "ID_VOLUMEN_ESPECIAL") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne
    @JoinColumn(name="ID_DETALLE", referencedColumnName="idDETALLE_PLANILLA")
    private DetallePlanillaEntity detallePlanilla;

    @ManyToMany(mappedBy="listOfPlanillas", targetEntity=EmpleadosEntity.class)
    private List<EmpleadosEntity> listOfEmpleados;

    @ManyToOne
    @JoinColumn(name="ID_VOLUMEN_ESPECIAL", referencedColumnName="idVOLUMEN")
    private VolumenTrabajoEspecialEntity volumenTrabajoEspecial;

    @ManyToOne
    @JoinColumn(name="ID_ESTADO", referencedColumnName="idESTADOS")
    private EstadosEntity estados     ;

    @ManyToOne
    @JoinColumn(name="ID_PUESTO_TRABAJO", referencedColumnName="idPUESTO DE TRABAJO", insertable=false, updatable=false)
    private PuestoDeTrabajoEntity puestoDeTrabajo;

    @ManyToOne
    @JoinColumn(name="ID_TIPO_FECHA", referencedColumnName="idTIPO_FECHA")
    private TipoFechaEntity tipoFecha   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PlanillasEntity() {
		super();
		this.compositePrimaryKey = new PlanillasEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setIdplanillas( Integer idplanillas ) {
        this.compositePrimaryKey.setIdplanillas( idplanillas ) ;
    }
    public Integer getIdplanillas() {
        return this.compositePrimaryKey.getIdplanillas() ;
    }
    public void setFecha( Date fecha ) {
        this.compositePrimaryKey.setFecha( fecha ) ;
    }
    public Date getFecha() {
        return this.compositePrimaryKey.getFecha() ;
    }
    public void setIdPuestoTrabajo( Integer idPuestoTrabajo ) {
        this.compositePrimaryKey.setIdPuestoTrabajo( idPuestoTrabajo ) ;
    }
    public Integer getIdPuestoTrabajo() {
        return this.compositePrimaryKey.getIdPuestoTrabajo() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : OBSERVACIONES ( VARCHAR ) 
    public void setObservaciones( String observaciones ) {
        this.observaciones = observaciones;
    }
    public String getObservaciones() {
        return this.observaciones;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDetallePlanilla( DetallePlanillaEntity detallePlanilla ) {
        this.detallePlanilla = detallePlanilla;
    }
    public DetallePlanillaEntity getDetallePlanilla() {
        return this.detallePlanilla;
    }

    public void setListOfEmpleados( List<EmpleadosEntity> listOfEmpleados ) {
        this.listOfEmpleados = listOfEmpleados;
    }
    public List<EmpleadosEntity> getListOfEmpleados() {
        return this.listOfEmpleados;
    }

    public void setVolumenTrabajoEspecial( VolumenTrabajoEspecialEntity volumenTrabajoEspecial ) {
        this.volumenTrabajoEspecial = volumenTrabajoEspecial;
    }
    public VolumenTrabajoEspecialEntity getVolumenTrabajoEspecial() {
        return this.volumenTrabajoEspecial;
    }

    public void setEstados( EstadosEntity estados ) {
        this.estados = estados;
    }
    public EstadosEntity getEstados() {
        return this.estados;
    }

    public void setPuestoDeTrabajo( PuestoDeTrabajoEntity puestoDeTrabajo ) {
        this.puestoDeTrabajo = puestoDeTrabajo;
    }
    public PuestoDeTrabajoEntity getPuestoDeTrabajo() {
        return this.puestoDeTrabajo;
    }

    public void setTipoFecha( TipoFechaEntity tipoFecha ) {
        this.tipoFecha = tipoFecha;
    }
    public TipoFechaEntity getTipoFecha() {
        return this.tipoFecha;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(observaciones);
        return sb.toString(); 
    } 

}
