/*
 * Created on 17 oct 2015 ( Time 10:46:16 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.model.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "PlanillasHasEmpleadosEntity" ( stored in table "planillas_has_empleados" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class PlanillasHasEmpleadosEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="PLANILLAS_idPLANILLAS", nullable=false)
    private Integer    planillasIdplanillas ;
    
    @Column(name="EMPLEADOS_idEMPLEADOS", nullable=false)
    private Integer    empleadosIdempleados ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public PlanillasHasEmpleadosEntityKey() {
        super();
    }

    public PlanillasHasEmpleadosEntityKey( Integer planillasIdplanillas, Integer empleadosIdempleados ) {
        super();
        this.planillasIdplanillas = planillasIdplanillas ;
        this.empleadosIdempleados = empleadosIdempleados ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setPlanillasIdplanillas( Integer value ) {
        this.planillasIdplanillas = value;
    }
    public Integer getPlanillasIdplanillas() {
        return this.planillasIdplanillas;
    }

    public void setEmpleadosIdempleados( Integer value ) {
        this.empleadosIdempleados = value;
    }
    public Integer getEmpleadosIdempleados() {
        return this.empleadosIdempleados;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		PlanillasHasEmpleadosEntityKey other = (PlanillasHasEmpleadosEntityKey) obj; 
		//--- Attribute planillasIdplanillas
		if ( planillasIdplanillas == null ) { 
			if ( other.planillasIdplanillas != null ) 
				return false ; 
		} else if ( ! planillasIdplanillas.equals(other.planillasIdplanillas) ) 
			return false ; 
		//--- Attribute empleadosIdempleados
		if ( empleadosIdempleados == null ) { 
			if ( other.empleadosIdempleados != null ) 
				return false ; 
		} else if ( ! empleadosIdempleados.equals(other.empleadosIdempleados) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute planillasIdplanillas
		result = prime * result + ((planillasIdplanillas == null) ? 0 : planillasIdplanillas.hashCode() ) ; 
		//--- Attribute empleadosIdempleados
		result = prime * result + ((empleadosIdempleados == null) ? 0 : empleadosIdempleados.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(planillasIdplanillas); 
		sb.append("|"); 
		sb.append(empleadosIdempleados); 
        return sb.toString();
    }
}
