/*
 * Created on 17 oct 2015 ( Time 10:46:16 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  


package org.sun.resorts.holidays.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "turnos_de_trabajo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="turnos_de_trabajo")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TurnosDeTrabajoEntity.countAll", query="SELECT COUNT(x) FROM TurnosDeTrabajoEntity x" )
} )
public class TurnosDeTrabajoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private TurnosDeTrabajoEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOMBRE", nullable=false, length=45)
    private String     nombre       ;

    @Column(name="DESCRIPCION", length=65)
    private String     descripcion  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="turnosDeTrabajo", targetEntity=HorarioEntity.class)
    private List<HorarioEntity> listOfHorario;

    @OneToMany(mappedBy="turnosDeTrabajo", targetEntity=TurnosTrabajoEspecialesEntity.class)
    private List<TurnosTrabajoEspecialesEntity> listOfTurnosTrabajoEspeciales;

    @ManyToOne
    @JoinColumn(name="ID_PUESTO_TRABAJO", referencedColumnName="idPUESTO_DE_TRABAJO", insertable=false, updatable=false)
    private PuestoDeTrabajoEntity puestoDeTrabajo;

    @OneToMany(mappedBy="turnosDeTrabajo", targetEntity=EmpleadosEntity.class)
    private List<EmpleadosEntity> listOfEmpleados;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TurnosDeTrabajoEntity() {
		super();
		this.compositePrimaryKey = new TurnosDeTrabajoEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setIdturnosDeTrabajo( Integer idturnosDeTrabajo ) {
        this.compositePrimaryKey.setIdturnosDeTrabajo( idturnosDeTrabajo ) ;
    }
    public Integer getIdturnosDeTrabajo() {
        return this.compositePrimaryKey.getIdturnosDeTrabajo() ;
    }
    public void setIdPuestoTrabajo( Integer idPuestoTrabajo ) {
        this.compositePrimaryKey.setIdPuestoTrabajo( idPuestoTrabajo ) ;
    }
    public Integer getIdPuestoTrabajo() {
        return this.compositePrimaryKey.getIdPuestoTrabajo() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOMBRE ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : DESCRIPCION ( VARCHAR ) 
    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfHorario( List<HorarioEntity> listOfHorario ) {
        this.listOfHorario = listOfHorario;
    }
    public List<HorarioEntity> getListOfHorario() {
        return this.listOfHorario;
    }

    public void setListOfTurnosTrabajoEspeciales( List<TurnosTrabajoEspecialesEntity> listOfTurnosTrabajoEspeciales ) {
        this.listOfTurnosTrabajoEspeciales = listOfTurnosTrabajoEspeciales;
    }
    public List<TurnosTrabajoEspecialesEntity> getListOfTurnosTrabajoEspeciales() {
        return this.listOfTurnosTrabajoEspeciales;
    }

    public void setPuestoDeTrabajo( PuestoDeTrabajoEntity puestoDeTrabajo ) {
        this.puestoDeTrabajo = puestoDeTrabajo;
    }
    public PuestoDeTrabajoEntity getPuestoDeTrabajo() {
        return this.puestoDeTrabajo;
    }

    public void setListOfEmpleados( List<EmpleadosEntity> listOfEmpleados ) {
        this.listOfEmpleados = listOfEmpleados;
    }
    public List<EmpleadosEntity> getListOfEmpleados() {
        return this.listOfEmpleados;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(descripcion);
        return sb.toString(); 
    } 

}
