/*
 * Created on 31 oct 2015 ( Time 10:51:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.Perfiles;
import org.sun.resorts.holidays.model.jpa.PerfilesEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PerfilesServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PerfilesServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PerfilesEntity' to 'Perfiles'
	 * @param perfilesEntity
	 */
	public Perfiles mapPerfilesEntityToPerfiles(PerfilesEntity perfilesEntity) {
		if(perfilesEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Perfiles perfiles = map(perfilesEntity, Perfiles.class);

		return perfiles;
	}
	
	/**
	 * Mapping from 'Perfiles' to 'PerfilesEntity'
	 * @param perfiles
	 * @param perfilesEntity
	 */
	public void mapPerfilesToPerfilesEntity(Perfiles perfiles, PerfilesEntity perfilesEntity) {
		if(perfiles == null) {
			return;
		}

		//--- Generic mapping 
		map(perfiles, perfilesEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}