/*
 * Created on 31 oct 2015 ( Time 10:51:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.TurnosDeTrabajoHasDetallePlanilla;
import org.sun.resorts.holidays.model.jpa.TurnosDeTrabajoHasDetallePlanillaEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TurnosDeTrabajoHasDetallePlanillaServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TurnosDeTrabajoHasDetallePlanillaServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TurnosDeTrabajoHasDetallePlanillaEntity' to 'TurnosDeTrabajoHasDetallePlanilla'
	 * @param turnosDeTrabajoHasDetallePlanillaEntity
	 */
	public TurnosDeTrabajoHasDetallePlanilla mapTurnosDeTrabajoHasDetallePlanillaEntityToTurnosDeTrabajoHasDetallePlanilla(TurnosDeTrabajoHasDetallePlanillaEntity turnosDeTrabajoHasDetallePlanillaEntity) {
		if(turnosDeTrabajoHasDetallePlanillaEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TurnosDeTrabajoHasDetallePlanilla turnosDeTrabajoHasDetallePlanilla = map(turnosDeTrabajoHasDetallePlanillaEntity, TurnosDeTrabajoHasDetallePlanilla.class);

		return turnosDeTrabajoHasDetallePlanilla;
	}
	
	/**
	 * Mapping from 'TurnosDeTrabajoHasDetallePlanilla' to 'TurnosDeTrabajoHasDetallePlanillaEntity'
	 * @param turnosDeTrabajoHasDetallePlanilla
	 * @param turnosDeTrabajoHasDetallePlanillaEntity
	 */
	public void mapTurnosDeTrabajoHasDetallePlanillaToTurnosDeTrabajoHasDetallePlanillaEntity(TurnosDeTrabajoHasDetallePlanilla turnosDeTrabajoHasDetallePlanilla, TurnosDeTrabajoHasDetallePlanillaEntity turnosDeTrabajoHasDetallePlanillaEntity) {
		if(turnosDeTrabajoHasDetallePlanilla == null) {
			return;
		}

		//--- Generic mapping 
		map(turnosDeTrabajoHasDetallePlanilla, turnosDeTrabajoHasDetallePlanillaEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}