/*
 * Created on 31 oct 2015 ( Time 10:51:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.Usuarios;
import org.sun.resorts.holidays.model.jpa.UsuariosEntity;
import org.sun.resorts.holidays.model.jpa.EmpleadosEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UsuariosServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UsuariosServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'UsuariosEntity' to 'Usuarios'
	 * @param usuariosEntity
	 */
	public Usuarios mapUsuariosEntityToUsuarios(UsuariosEntity usuariosEntity) {
		if(usuariosEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Usuarios usuarios = map(usuariosEntity, Usuarios.class);

		//--- Link mapping ( link to Empleados )
		if(usuariosEntity.getEmpleados() != null) {
			usuarios.setEmpleadosIdempleados(usuariosEntity.getEmpleados().getIdempleados());
		}
		return usuarios;
	}
	
	/**
	 * Mapping from 'Usuarios' to 'UsuariosEntity'
	 * @param usuarios
	 * @param usuariosEntity
	 */
	public void mapUsuariosToUsuariosEntity(Usuarios usuarios, UsuariosEntity usuariosEntity) {
		if(usuarios == null) {
			return;
		}

		//--- Generic mapping 
		map(usuarios, usuariosEntity);

		//--- Link mapping ( link : usuarios )
		if( hasLinkToEmpleados(usuarios) ) {
			EmpleadosEntity empleados1 = new EmpleadosEntity();
			empleados1.setIdempleados( usuarios.getEmpleadosIdempleados() );
			usuariosEntity.setEmpleados( empleados1 );
		} else {
			usuariosEntity.setEmpleados( null );
		}

	}
	
	/**
	 * Verify that Empleados id is valid.
	 * @param Empleados Empleados
	 * @return boolean
	 */
	private boolean hasLinkToEmpleados(Usuarios usuarios) {
		if(usuarios.getEmpleadosIdempleados() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}