/*
 * Created on 31 oct 2015 ( Time 10:51:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.Planillas;
import org.sun.resorts.holidays.model.jpa.PlanillasEntity;
import org.sun.resorts.holidays.model.jpa.PuestoDeTrabajoEntity;
import org.sun.resorts.holidays.model.jpa.EstadosEntity;
import org.sun.resorts.holidays.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PlanillasServiceMapperTest {

	private PlanillasServiceMapper planillasServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		planillasServiceMapper = new PlanillasServiceMapper();
		planillasServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PlanillasEntity' to 'Planillas'
	 * @param planillasEntity
	 */
	@Test
	public void testMapPlanillasEntityToPlanillas() {
		// Given
		PlanillasEntity planillasEntity = new PlanillasEntity();
		planillasEntity.setFechaInicio(mockValues.nextDate());
		planillasEntity.setIdDetalle(mockValues.nextInteger());
		planillasEntity.setFechaFin(mockValues.nextDate());
		planillasEntity.setDescripcion(mockValues.nextString(65));
		planillasEntity.setPuestoDeTrabajo(new PuestoDeTrabajoEntity());
		planillasEntity.getPuestoDeTrabajo().setIdpuestoDeTrabajo(mockValues.nextInteger());
		planillasEntity.setEstados(new EstadosEntity());
		planillasEntity.getEstados().setIdestados(mockValues.nextInteger());
		
		// When
		Planillas planillas = planillasServiceMapper.mapPlanillasEntityToPlanillas(planillasEntity);
		
		// Then
		assertEquals(planillasEntity.getFechaInicio(), planillas.getFechaInicio());
		assertEquals(planillasEntity.getIdDetalle(), planillas.getIdDetalle());
		assertEquals(planillasEntity.getFechaFin(), planillas.getFechaFin());
		assertEquals(planillasEntity.getDescripcion(), planillas.getDescripcion());
		assertEquals(planillasEntity.getPuestoDeTrabajo().getIdpuestoDeTrabajo(), planillas.getIdPuestoTrabajo());
		assertEquals(planillasEntity.getEstados().getIdestados(), planillas.getIdEstado());
	}
	
	/**
	 * Test : Mapping from 'Planillas' to 'PlanillasEntity'
	 */
	@Test
	public void testMapPlanillasToPlanillasEntity() {
		// Given
		Planillas planillas = new Planillas();
		planillas.setFechaInicio(mockValues.nextDate());
		planillas.setIdDetalle(mockValues.nextInteger());
		planillas.setFechaFin(mockValues.nextDate());
		planillas.setDescripcion(mockValues.nextString(65));
		planillas.setIdPuestoTrabajo(mockValues.nextInteger());
		planillas.setIdEstado(mockValues.nextInteger());

		PlanillasEntity planillasEntity = new PlanillasEntity();
		
		// When
		planillasServiceMapper.mapPlanillasToPlanillasEntity(planillas, planillasEntity);
		
		// Then
		assertEquals(planillas.getFechaInicio(), planillasEntity.getFechaInicio());
		assertEquals(planillas.getIdDetalle(), planillasEntity.getIdDetalle());
		assertEquals(planillas.getFechaFin(), planillasEntity.getFechaFin());
		assertEquals(planillas.getDescripcion(), planillasEntity.getDescripcion());
		assertEquals(planillas.getIdPuestoTrabajo(), planillasEntity.getPuestoDeTrabajo().getIdpuestoDeTrabajo());
		assertEquals(planillas.getIdEstado(), planillasEntity.getEstados().getIdestados());
	}

}