/*
 * Created on 31 oct 2015 ( Time 10:51:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.sun.resorts.holidays.model.TurnosDeTrabajoHasDetallePlanilla;
import org.sun.resorts.holidays.model.jpa.TurnosDeTrabajoHasDetallePlanillaEntity;
import org.sun.resorts.holidays.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class TurnosDeTrabajoHasDetallePlanillaServiceMapperTest {

	private TurnosDeTrabajoHasDetallePlanillaServiceMapper turnosDeTrabajoHasDetallePlanillaServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		turnosDeTrabajoHasDetallePlanillaServiceMapper = new TurnosDeTrabajoHasDetallePlanillaServiceMapper();
		turnosDeTrabajoHasDetallePlanillaServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'TurnosDeTrabajoHasDetallePlanillaEntity' to 'TurnosDeTrabajoHasDetallePlanilla'
	 * @param turnosDeTrabajoHasDetallePlanillaEntity
	 */
	@Test
	public void testMapTurnosDeTrabajoHasDetallePlanillaEntityToTurnosDeTrabajoHasDetallePlanilla() {
		// Given
		TurnosDeTrabajoHasDetallePlanillaEntity turnosDeTrabajoHasDetallePlanillaEntity = new TurnosDeTrabajoHasDetallePlanillaEntity();
		
		// When
		TurnosDeTrabajoHasDetallePlanilla turnosDeTrabajoHasDetallePlanilla = turnosDeTrabajoHasDetallePlanillaServiceMapper.mapTurnosDeTrabajoHasDetallePlanillaEntityToTurnosDeTrabajoHasDetallePlanilla(turnosDeTrabajoHasDetallePlanillaEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'TurnosDeTrabajoHasDetallePlanilla' to 'TurnosDeTrabajoHasDetallePlanillaEntity'
	 */
	@Test
	public void testMapTurnosDeTrabajoHasDetallePlanillaToTurnosDeTrabajoHasDetallePlanillaEntity() {
		// Given
		TurnosDeTrabajoHasDetallePlanilla turnosDeTrabajoHasDetallePlanilla = new TurnosDeTrabajoHasDetallePlanilla();

		TurnosDeTrabajoHasDetallePlanillaEntity turnosDeTrabajoHasDetallePlanillaEntity = new TurnosDeTrabajoHasDetallePlanillaEntity();
		
		// When
		turnosDeTrabajoHasDetallePlanillaServiceMapper.mapTurnosDeTrabajoHasDetallePlanillaToTurnosDeTrabajoHasDetallePlanillaEntity(turnosDeTrabajoHasDetallePlanilla, turnosDeTrabajoHasDetallePlanillaEntity);
		
		// Then
	}

}