/*
 * Created on 31 oct 2015 ( Time 10:51:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service;

import java.util.List;

import org.sun.resorts.holidays.model.CentrosDeTrabajo;

/**
 * Business Service Interface for entity CentrosDeTrabajo.
 */
public interface CentrosDeTrabajoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idcentrosDeTrabajo
	 * @return entity
	 */
	CentrosDeTrabajo findById( Integer idcentrosDeTrabajo  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<CentrosDeTrabajo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CentrosDeTrabajo save(CentrosDeTrabajo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CentrosDeTrabajo update(CentrosDeTrabajo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CentrosDeTrabajo create(CentrosDeTrabajo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idcentrosDeTrabajo
	 */
	void delete( Integer idcentrosDeTrabajo );


}
