/*
 * Created on 31 oct 2015 ( Time 10:51:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service;

import java.util.List;

import org.sun.resorts.holidays.model.Empleados;

/**
 * Business Service Interface for entity Empleados.
 */
public interface EmpleadosService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idempleados
	 * @return entity
	 */
	Empleados findById( Integer idempleados  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Empleados> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Empleados save(Empleados entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Empleados update(Empleados entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Empleados create(Empleados entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idempleados
	 */
	void delete( Integer idempleados );


}
