/*
 * Created on 31 oct 2015 ( Time 10:51:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service;

import java.util.List;

import org.sun.resorts.holidays.model.Estados;

/**
 * Business Service Interface for entity Estados.
 */
public interface EstadosService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idestados
	 * @return entity
	 */
	Estados findById( Integer idestados  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Estados> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Estados save(Estados entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Estados update(Estados entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Estados create(Estados entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idestados
	 */
	void delete( Integer idestados );


}
