/*
 * Created on 31 oct 2015 ( Time 10:51:34 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service;

import java.util.List;

import org.sun.resorts.holidays.model.Perfiles;

/**
 * Business Service Interface for entity Perfiles.
 */
public interface PerfilesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idperfiles
	 * @return entity
	 */
	Perfiles findById( Integer idperfiles  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Perfiles> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Perfiles save(Perfiles entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Perfiles update(Perfiles entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Perfiles create(Perfiles entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idperfiles
	 */
	void delete( Integer idperfiles );


}
