/*
 * Created on 31 oct 2015 ( Time 10:51:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.persistence.service;

import java.util.List;

import org.sun.resorts.holidays.model.PuestoDeTrabajo;

/**
 * Business Service Interface for entity PuestoDeTrabajo.
 */
public interface PuestoDeTrabajoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idpuestoDeTrabajo
	 * @return entity
	 */
	PuestoDeTrabajo findById( Integer idpuestoDeTrabajo  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PuestoDeTrabajo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PuestoDeTrabajo save(PuestoDeTrabajo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PuestoDeTrabajo update(PuestoDeTrabajo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PuestoDeTrabajo create(PuestoDeTrabajo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idpuestoDeTrabajo
	 */
	void delete( Integer idpuestoDeTrabajo );


}
