/*
 * Java bean class for entity table centros_de_trabajo 
 * Created on 28 oct 2015 ( Date ISO 2015-10-28 - Time 21:52:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;


/**
 * Entity bean for table "centros_de_trabajo"
 * 
 * @author Telosys Tools Generator
 *
 */
public class CentrosDeTrabajo implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idcentrosDeTrabajo ; // Primary Key

    private String     nombre       ;
    private String     descripcion  ;
    private Boolean    parking      ;
    private Boolean    piscina      ;
    private Integer    numHabitaciones ;
    private Integer    numEstrellas ;
    private Integer    idAdministrador ;
    private Integer    idDireccion  ;

    /**
     * Default constructor
     */
    public CentrosDeTrabajo()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idcentrosDeTrabajo" field value
     * This field is mapped on the database column "idCENTROS_DE_TRABAJO" ( type "INT", NotNull : true ) 
     * @param idcentrosDeTrabajo
     */
	public void setIdcentrosDeTrabajo( Integer idcentrosDeTrabajo )
    {
        this.idcentrosDeTrabajo = idcentrosDeTrabajo ;
    }
    /**
     * Get the "idcentrosDeTrabajo" field value
     * This field is mapped on the database column "idCENTROS_DE_TRABAJO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdcentrosDeTrabajo()
    {
        return this.idcentrosDeTrabajo;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOMBRE ( VARCHAR ) 
    /**
     * Set the "nombre" field value
     * This field is mapped on the database column "NOMBRE" ( type "VARCHAR", NotNull : false ) 
     * @param nombre
     */
    public void setNombre( String nombre )
    {
        this.nombre = nombre;
    }
    /**
     * Get the "nombre" field value
     * This field is mapped on the database column "NOMBRE" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getNombre()
    {
        return this.nombre;
    }

    //--- DATABASE MAPPING : DESCRIPCION ( VARCHAR ) 
    /**
     * Set the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : false ) 
     * @param descripcion
     */
    public void setDescripcion( String descripcion )
    {
        this.descripcion = descripcion;
    }
    /**
     * Get the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getDescripcion()
    {
        return this.descripcion;
    }

    //--- DATABASE MAPPING : PARKING ( BIT ) 
    /**
     * Set the "parking" field value
     * This field is mapped on the database column "PARKING" ( type "BIT", NotNull : true ) 
     * @param parking
     */
    public void setParking( Boolean parking )
    {
        this.parking = parking;
    }
    /**
     * Get the "parking" field value
     * This field is mapped on the database column "PARKING" ( type "BIT", NotNull : true ) 
     * @return the field value
     */
    public Boolean getParking()
    {
        return this.parking;
    }

    //--- DATABASE MAPPING : PISCINA ( BIT ) 
    /**
     * Set the "piscina" field value
     * This field is mapped on the database column "PISCINA" ( type "BIT", NotNull : true ) 
     * @param piscina
     */
    public void setPiscina( Boolean piscina )
    {
        this.piscina = piscina;
    }
    /**
     * Get the "piscina" field value
     * This field is mapped on the database column "PISCINA" ( type "BIT", NotNull : true ) 
     * @return the field value
     */
    public Boolean getPiscina()
    {
        return this.piscina;
    }

    //--- DATABASE MAPPING : NUM_HABITACIONES ( INT ) 
    /**
     * Set the "numHabitaciones" field value
     * This field is mapped on the database column "NUM_HABITACIONES" ( type "INT", NotNull : true ) 
     * @param numHabitaciones
     */
    public void setNumHabitaciones( Integer numHabitaciones )
    {
        this.numHabitaciones = numHabitaciones;
    }
    /**
     * Get the "numHabitaciones" field value
     * This field is mapped on the database column "NUM_HABITACIONES" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getNumHabitaciones()
    {
        return this.numHabitaciones;
    }

    //--- DATABASE MAPPING : NUM_ESTRELLAS ( INT ) 
    /**
     * Set the "numEstrellas" field value
     * This field is mapped on the database column "NUM_ESTRELLAS" ( type "INT", NotNull : true ) 
     * @param numEstrellas
     */
    public void setNumEstrellas( Integer numEstrellas )
    {
        this.numEstrellas = numEstrellas;
    }
    /**
     * Get the "numEstrellas" field value
     * This field is mapped on the database column "NUM_ESTRELLAS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getNumEstrellas()
    {
        return this.numEstrellas;
    }

    //--- DATABASE MAPPING : ID_ADMINISTRADOR ( INT ) 
    /**
     * Set the "idAdministrador" field value
     * This field is mapped on the database column "ID_ADMINISTRADOR" ( type "INT", NotNull : false ) 
     * @param idAdministrador
     */
    public void setIdAdministrador( Integer idAdministrador )
    {
        this.idAdministrador = idAdministrador;
    }
    /**
     * Get the "idAdministrador" field value
     * This field is mapped on the database column "ID_ADMINISTRADOR" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdAdministrador()
    {
        return this.idAdministrador;
    }

    //--- DATABASE MAPPING : ID_DIRECCION ( INT ) 
    /**
     * Set the "idDireccion" field value
     * This field is mapped on the database column "ID_DIRECCION" ( type "INT", NotNull : false ) 
     * @param idDireccion
     */
    public void setIdDireccion( Integer idDireccion )
    {
        this.idDireccion = idDireccion;
    }
    /**
     * Get the "idDireccion" field value
     * This field is mapped on the database column "ID_DIRECCION" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdDireccion()
    {
        return this.idDireccion;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idcentrosDeTrabajo);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(parking);
        sb.append("|");
        sb.append(piscina);
        sb.append("|");
        sb.append(numHabitaciones);
        sb.append("|");
        sb.append(numEstrellas);
        sb.append("|");
        sb.append(idAdministrador);
        sb.append("|");
        sb.append(idDireccion);
        return sb.toString(); 
    } 


}
