/*
 * Java bean class for entity table detalle_planilla 
 * Created on 31 oct 2015 ( Date ISO 2015-10-31 - Time 10:15:17 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "detalle_planilla"
 * 
 * @author Telosys Tools Generator
 *
 */
public class DetallePlanilla implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idDetalle    ; // Primary Key
    private Integer    planillasIdplanillas ; // Primary Key

    private Date       dia          ;
    private Integer    tipoFechaIdtipoFecha ;

    /**
     * Default constructor
     */
    public DetallePlanilla()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idDetalle" field value
     * This field is mapped on the database column "ID_DETALLE" ( type "INT", NotNull : true ) 
     * @param idDetalle
     */
	public void setIdDetalle( Integer idDetalle )
    {
        this.idDetalle = idDetalle ;
    }
    /**
     * Get the "idDetalle" field value
     * This field is mapped on the database column "ID_DETALLE" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdDetalle()
    {
        return this.idDetalle;
    }
    /**
     * Set the "planillasIdplanillas" field value
     * This field is mapped on the database column "PLANILLAS_idPLANILLAS" ( type "INT", NotNull : true ) 
     * @param planillasIdplanillas
     */
	public void setPlanillasIdplanillas( Integer planillasIdplanillas )
    {
        this.planillasIdplanillas = planillasIdplanillas ;
    }
    /**
     * Get the "planillasIdplanillas" field value
     * This field is mapped on the database column "PLANILLAS_idPLANILLAS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getPlanillasIdplanillas()
    {
        return this.planillasIdplanillas;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DIA ( DATE ) 
    /**
     * Set the "dia" field value
     * This field is mapped on the database column "DIA" ( type "DATE", NotNull : true ) 
     * @param dia
     */
    public void setDia( Date dia )
    {
        this.dia = dia;
    }
    /**
     * Get the "dia" field value
     * This field is mapped on the database column "DIA" ( type "DATE", NotNull : true ) 
     * @return the field value
     */
    public Date getDia()
    {
        return this.dia;
    }

    //--- DATABASE MAPPING : TIPO_FECHA_idTIPO_FECHA ( INT ) 
    /**
     * Set the "tipoFechaIdtipoFecha" field value
     * This field is mapped on the database column "TIPO_FECHA_idTIPO_FECHA" ( type "INT", NotNull : true ) 
     * @param tipoFechaIdtipoFecha
     */
    public void setTipoFechaIdtipoFecha( Integer tipoFechaIdtipoFecha )
    {
        this.tipoFechaIdtipoFecha = tipoFechaIdtipoFecha;
    }
    /**
     * Get the "tipoFechaIdtipoFecha" field value
     * This field is mapped on the database column "TIPO_FECHA_idTIPO_FECHA" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getTipoFechaIdtipoFecha()
    {
        return this.tipoFechaIdtipoFecha;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idDetalle);
        sb.append("|");
        sb.append(dia);
        sb.append("|");
        sb.append(planillasIdplanillas);
        sb.append("|");
        sb.append(tipoFechaIdtipoFecha);
        return sb.toString(); 
    } 


}
