/*
 * Java bean class for entity table empleados 
 * Created on 31 oct 2015 ( Date ISO 2015-10-31 - Time 10:15:17 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "empleados"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Empleados implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idempleados  ; // Primary Key

    private String     nombre       ;
    private String     apellido1    ;
    private String     apellido2    ;
    private String     telefonoMovil ;
    private String     telefonoFijo ;
    private Date       fechaNacimiento ;
    private Date       fechaIncorporacion ;
    private Integer    idDireccion  ;
    private String     dni          ;
    private Integer    numDiasVacaciones ;
    private String     email        ;
    private Integer    perfilesIdperfiles ;
    private Integer    idTurnoTrabajo ;
    private Integer    numDiasFestivosPendientes ;

    /**
     * Default constructor
     */
    public Empleados()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idempleados" field value
     * This field is mapped on the database column "idEMPLEADOS" ( type "INT", NotNull : true ) 
     * @param idempleados
     */
	public void setIdempleados( Integer idempleados )
    {
        this.idempleados = idempleados ;
    }
    /**
     * Get the "idempleados" field value
     * This field is mapped on the database column "idEMPLEADOS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdempleados()
    {
        return this.idempleados;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOMBRE ( VARCHAR ) 
    /**
     * Set the "nombre" field value
     * This field is mapped on the database column "NOMBRE" ( type "VARCHAR", NotNull : true ) 
     * @param nombre
     */
    public void setNombre( String nombre )
    {
        this.nombre = nombre;
    }
    /**
     * Get the "nombre" field value
     * This field is mapped on the database column "NOMBRE" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getNombre()
    {
        return this.nombre;
    }

    //--- DATABASE MAPPING : APELLIDO1 ( VARCHAR ) 
    /**
     * Set the "apellido1" field value
     * This field is mapped on the database column "APELLIDO1" ( type "VARCHAR", NotNull : false ) 
     * @param apellido1
     */
    public void setApellido1( String apellido1 )
    {
        this.apellido1 = apellido1;
    }
    /**
     * Get the "apellido1" field value
     * This field is mapped on the database column "APELLIDO1" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getApellido1()
    {
        return this.apellido1;
    }

    //--- DATABASE MAPPING : APELLIDO2 ( VARCHAR ) 
    /**
     * Set the "apellido2" field value
     * This field is mapped on the database column "APELLIDO2" ( type "VARCHAR", NotNull : false ) 
     * @param apellido2
     */
    public void setApellido2( String apellido2 )
    {
        this.apellido2 = apellido2;
    }
    /**
     * Get the "apellido2" field value
     * This field is mapped on the database column "APELLIDO2" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getApellido2()
    {
        return this.apellido2;
    }

    //--- DATABASE MAPPING : TELEFONO_MOVIL ( VARCHAR ) 
    /**
     * Set the "telefonoMovil" field value
     * This field is mapped on the database column "TELEFONO_MOVIL" ( type "VARCHAR", NotNull : true ) 
     * @param telefonoMovil
     */
    public void setTelefonoMovil( String telefonoMovil )
    {
        this.telefonoMovil = telefonoMovil;
    }
    /**
     * Get the "telefonoMovil" field value
     * This field is mapped on the database column "TELEFONO_MOVIL" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getTelefonoMovil()
    {
        return this.telefonoMovil;
    }

    //--- DATABASE MAPPING : TELEFONO_FIJO ( VARCHAR ) 
    /**
     * Set the "telefonoFijo" field value
     * This field is mapped on the database column "TELEFONO_FIJO" ( type "VARCHAR", NotNull : false ) 
     * @param telefonoFijo
     */
    public void setTelefonoFijo( String telefonoFijo )
    {
        this.telefonoFijo = telefonoFijo;
    }
    /**
     * Get the "telefonoFijo" field value
     * This field is mapped on the database column "TELEFONO_FIJO" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getTelefonoFijo()
    {
        return this.telefonoFijo;
    }

    //--- DATABASE MAPPING : FECHA_NACIMIENTO ( DATE ) 
    /**
     * Set the "fechaNacimiento" field value
     * This field is mapped on the database column "FECHA_NACIMIENTO" ( type "DATE", NotNull : true ) 
     * @param fechaNacimiento
     */
    public void setFechaNacimiento( Date fechaNacimiento )
    {
        this.fechaNacimiento = fechaNacimiento;
    }
    /**
     * Get the "fechaNacimiento" field value
     * This field is mapped on the database column "FECHA_NACIMIENTO" ( type "DATE", NotNull : true ) 
     * @return the field value
     */
    public Date getFechaNacimiento()
    {
        return this.fechaNacimiento;
    }

    //--- DATABASE MAPPING : FECHA_INCORPORACION ( DATE ) 
    /**
     * Set the "fechaIncorporacion" field value
     * This field is mapped on the database column "FECHA_INCORPORACION" ( type "DATE", NotNull : true ) 
     * @param fechaIncorporacion
     */
    public void setFechaIncorporacion( Date fechaIncorporacion )
    {
        this.fechaIncorporacion = fechaIncorporacion;
    }
    /**
     * Get the "fechaIncorporacion" field value
     * This field is mapped on the database column "FECHA_INCORPORACION" ( type "DATE", NotNull : true ) 
     * @return the field value
     */
    public Date getFechaIncorporacion()
    {
        return this.fechaIncorporacion;
    }

    //--- DATABASE MAPPING : ID_DIRECCION ( INT ) 
    /**
     * Set the "idDireccion" field value
     * This field is mapped on the database column "ID_DIRECCION" ( type "INT", NotNull : false ) 
     * @param idDireccion
     */
    public void setIdDireccion( Integer idDireccion )
    {
        this.idDireccion = idDireccion;
    }
    /**
     * Get the "idDireccion" field value
     * This field is mapped on the database column "ID_DIRECCION" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdDireccion()
    {
        return this.idDireccion;
    }

    //--- DATABASE MAPPING : DNI ( VARCHAR ) 
    /**
     * Set the "dni" field value
     * This field is mapped on the database column "DNI" ( type "VARCHAR", NotNull : true ) 
     * @param dni
     */
    public void setDni( String dni )
    {
        this.dni = dni;
    }
    /**
     * Get the "dni" field value
     * This field is mapped on the database column "DNI" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getDni()
    {
        return this.dni;
    }

    //--- DATABASE MAPPING : NUM_DIAS_VACACIONES ( INT ) 
    /**
     * Set the "numDiasVacaciones" field value
     * This field is mapped on the database column "NUM_DIAS_VACACIONES" ( type "INT", NotNull : true ) 
     * @param numDiasVacaciones
     */
    public void setNumDiasVacaciones( Integer numDiasVacaciones )
    {
        this.numDiasVacaciones = numDiasVacaciones;
    }
    /**
     * Get the "numDiasVacaciones" field value
     * This field is mapped on the database column "NUM_DIAS_VACACIONES" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getNumDiasVacaciones()
    {
        return this.numDiasVacaciones;
    }

    //--- DATABASE MAPPING : EMAIL ( VARCHAR ) 
    /**
     * Set the "email" field value
     * This field is mapped on the database column "EMAIL" ( type "VARCHAR", NotNull : true ) 
     * @param email
     */
    public void setEmail( String email )
    {
        this.email = email;
    }
    /**
     * Get the "email" field value
     * This field is mapped on the database column "EMAIL" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getEmail()
    {
        return this.email;
    }

    //--- DATABASE MAPPING : PERFILES_idPERFILES ( INT ) 
    /**
     * Set the "perfilesIdperfiles" field value
     * This field is mapped on the database column "PERFILES_idPERFILES" ( type "INT", NotNull : true ) 
     * @param perfilesIdperfiles
     */
    public void setPerfilesIdperfiles( Integer perfilesIdperfiles )
    {
        this.perfilesIdperfiles = perfilesIdperfiles;
    }
    /**
     * Get the "perfilesIdperfiles" field value
     * This field is mapped on the database column "PERFILES_idPERFILES" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getPerfilesIdperfiles()
    {
        return this.perfilesIdperfiles;
    }

    //--- DATABASE MAPPING : ID_TURNO_TRABAJO ( INT ) 
    /**
     * Set the "idTurnoTrabajo" field value
     * This field is mapped on the database column "ID_TURNO_TRABAJO" ( type "INT", NotNull : false ) 
     * @param idTurnoTrabajo
     */
    public void setIdTurnoTrabajo( Integer idTurnoTrabajo )
    {
        this.idTurnoTrabajo = idTurnoTrabajo;
    }
    /**
     * Get the "idTurnoTrabajo" field value
     * This field is mapped on the database column "ID_TURNO_TRABAJO" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdTurnoTrabajo()
    {
        return this.idTurnoTrabajo;
    }

    //--- DATABASE MAPPING : NUM_DIAS_FESTIVOS_PENDIENTES ( INT ) 
    /**
     * Set the "numDiasFestivosPendientes" field value
     * This field is mapped on the database column "NUM_DIAS_FESTIVOS_PENDIENTES" ( type "INT", NotNull : true ) 
     * @param numDiasFestivosPendientes
     */
    public void setNumDiasFestivosPendientes( Integer numDiasFestivosPendientes )
    {
        this.numDiasFestivosPendientes = numDiasFestivosPendientes;
    }
    /**
     * Get the "numDiasFestivosPendientes" field value
     * This field is mapped on the database column "NUM_DIAS_FESTIVOS_PENDIENTES" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getNumDiasFestivosPendientes()
    {
        return this.numDiasFestivosPendientes;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idempleados);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(apellido1);
        sb.append("|");
        sb.append(apellido2);
        sb.append("|");
        sb.append(telefonoMovil);
        sb.append("|");
        sb.append(telefonoFijo);
        sb.append("|");
        sb.append(fechaNacimiento);
        sb.append("|");
        sb.append(fechaIncorporacion);
        sb.append("|");
        sb.append(idDireccion);
        sb.append("|");
        sb.append(dni);
        sb.append("|");
        sb.append(numDiasVacaciones);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(perfilesIdperfiles);
        sb.append("|");
        sb.append(idTurnoTrabajo);
        sb.append("|");
        sb.append(numDiasFestivosPendientes);
        return sb.toString(); 
    } 


}
