/*
 * Java bean class for entity table estados 
 * Created on 28 oct 2015 ( Date ISO 2015-10-28 - Time 21:52:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;


/**
 * Entity bean for table "estados"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Estados implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idestados    ; // Primary Key

    private String     descripcion  ;

    /**
     * Default constructor
     */
    public Estados()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idestados" field value
     * This field is mapped on the database column "idESTADOS" ( type "INT", NotNull : true ) 
     * @param idestados
     */
	public void setIdestados( Integer idestados )
    {
        this.idestados = idestados ;
    }
    /**
     * Get the "idestados" field value
     * This field is mapped on the database column "idESTADOS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdestados()
    {
        return this.idestados;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DESCRIPCION ( VARCHAR ) 
    /**
     * Set the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : true ) 
     * @param descripcion
     */
    public void setDescripcion( String descripcion )
    {
        this.descripcion = descripcion;
    }
    /**
     * Get the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getDescripcion()
    {
        return this.descripcion;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idestados);
        sb.append("|");
        sb.append(descripcion);
        return sb.toString(); 
    } 


}
