/*
 * Java bean class for entity table horario 
 * Created on 28 oct 2015 ( Date ISO 2015-10-28 - Time 21:52:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "horario"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Horario implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idhorario    ; // Primary Key

    private Date       horaInicio   ;
    private Date       horaFin      ;
    private Date       horaInicioEspecial ;
    private Date       horaFinEspecial ;
    private Integer    idPuestoTrabajo ;
    private Integer    idTurnoTrabajo ;

    /**
     * Default constructor
     */
    public Horario()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idhorario" field value
     * This field is mapped on the database column "idHORARIO" ( type "INT", NotNull : true ) 
     * @param idhorario
     */
	public void setIdhorario( Integer idhorario )
    {
        this.idhorario = idhorario ;
    }
    /**
     * Get the "idhorario" field value
     * This field is mapped on the database column "idHORARIO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdhorario()
    {
        return this.idhorario;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : HORA_INICIO ( TIME ) 
    /**
     * Set the "horaInicio" field value
     * This field is mapped on the database column "HORA_INICIO" ( type "TIME", NotNull : true ) 
     * @param horaInicio
     */
    public void setHoraInicio( Date horaInicio )
    {
        this.horaInicio = horaInicio;
    }
    /**
     * Get the "horaInicio" field value
     * This field is mapped on the database column "HORA_INICIO" ( type "TIME", NotNull : true ) 
     * @return the field value
     */
    public Date getHoraInicio()
    {
        return this.horaInicio;
    }

    //--- DATABASE MAPPING : HORA_FIN ( TIME ) 
    /**
     * Set the "horaFin" field value
     * This field is mapped on the database column "HORA_FIN" ( type "TIME", NotNull : true ) 
     * @param horaFin
     */
    public void setHoraFin( Date horaFin )
    {
        this.horaFin = horaFin;
    }
    /**
     * Get the "horaFin" field value
     * This field is mapped on the database column "HORA_FIN" ( type "TIME", NotNull : true ) 
     * @return the field value
     */
    public Date getHoraFin()
    {
        return this.horaFin;
    }

    //--- DATABASE MAPPING : HORA_INICIO_ESPECIAL ( TIME ) 
    /**
     * Set the "horaInicioEspecial" field value
     * This field is mapped on the database column "HORA_INICIO_ESPECIAL" ( type "TIME", NotNull : false ) 
     * @param horaInicioEspecial
     */
    public void setHoraInicioEspecial( Date horaInicioEspecial )
    {
        this.horaInicioEspecial = horaInicioEspecial;
    }
    /**
     * Get the "horaInicioEspecial" field value
     * This field is mapped on the database column "HORA_INICIO_ESPECIAL" ( type "TIME", NotNull : false ) 
     * @return the field value
     */
    public Date getHoraInicioEspecial()
    {
        return this.horaInicioEspecial;
    }

    //--- DATABASE MAPPING : HORA_FIN_ESPECIAL ( TIME ) 
    /**
     * Set the "horaFinEspecial" field value
     * This field is mapped on the database column "HORA_FIN_ESPECIAL" ( type "TIME", NotNull : false ) 
     * @param horaFinEspecial
     */
    public void setHoraFinEspecial( Date horaFinEspecial )
    {
        this.horaFinEspecial = horaFinEspecial;
    }
    /**
     * Get the "horaFinEspecial" field value
     * This field is mapped on the database column "HORA_FIN_ESPECIAL" ( type "TIME", NotNull : false ) 
     * @return the field value
     */
    public Date getHoraFinEspecial()
    {
        return this.horaFinEspecial;
    }

    //--- DATABASE MAPPING : ID_PUESTO_TRABAJO ( INT ) 
    /**
     * Set the "idPuestoTrabajo" field value
     * This field is mapped on the database column "ID_PUESTO_TRABAJO" ( type "INT", NotNull : false ) 
     * @param idPuestoTrabajo
     */
    public void setIdPuestoTrabajo( Integer idPuestoTrabajo )
    {
        this.idPuestoTrabajo = idPuestoTrabajo;
    }
    /**
     * Get the "idPuestoTrabajo" field value
     * This field is mapped on the database column "ID_PUESTO_TRABAJO" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdPuestoTrabajo()
    {
        return this.idPuestoTrabajo;
    }

    //--- DATABASE MAPPING : ID_TURNO_TRABAJO ( INT ) 
    /**
     * Set the "idTurnoTrabajo" field value
     * This field is mapped on the database column "ID_TURNO_TRABAJO" ( type "INT", NotNull : false ) 
     * @param idTurnoTrabajo
     */
    public void setIdTurnoTrabajo( Integer idTurnoTrabajo )
    {
        this.idTurnoTrabajo = idTurnoTrabajo;
    }
    /**
     * Get the "idTurnoTrabajo" field value
     * This field is mapped on the database column "ID_TURNO_TRABAJO" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdTurnoTrabajo()
    {
        return this.idTurnoTrabajo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idhorario);
        sb.append("|");
        sb.append(horaInicio);
        sb.append("|");
        sb.append(horaFin);
        sb.append("|");
        sb.append(horaInicioEspecial);
        sb.append("|");
        sb.append(horaFinEspecial);
        sb.append("|");
        sb.append(idPuestoTrabajo);
        sb.append("|");
        sb.append(idTurnoTrabajo);
        return sb.toString(); 
    } 


}
