/*
 * Java bean class for entity table planillas_has_empleados 
 * Created on 28 oct 2015 ( Date ISO 2015-10-28 - Time 21:52:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;


/**
 * Entity bean for table "planillas_has_empleados"
 * 
 * @author Telosys Tools Generator
 *
 */
public class PlanillasHasEmpleados implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    planillasIdplanillas ; // Primary Key
    private Integer    empleadosIdempleados ; // Primary Key


    /**
     * Default constructor
     */
    public PlanillasHasEmpleados()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "planillasIdplanillas" field value
     * This field is mapped on the database column "PLANILLAS_idPLANILLAS" ( type "INT", NotNull : true ) 
     * @param planillasIdplanillas
     */
	public void setPlanillasIdplanillas( Integer planillasIdplanillas )
    {
        this.planillasIdplanillas = planillasIdplanillas ;
    }
    /**
     * Get the "planillasIdplanillas" field value
     * This field is mapped on the database column "PLANILLAS_idPLANILLAS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getPlanillasIdplanillas()
    {
        return this.planillasIdplanillas;
    }
    /**
     * Set the "empleadosIdempleados" field value
     * This field is mapped on the database column "EMPLEADOS_idEMPLEADOS" ( type "INT", NotNull : true ) 
     * @param empleadosIdempleados
     */
	public void setEmpleadosIdempleados( Integer empleadosIdempleados )
    {
        this.empleadosIdempleados = empleadosIdempleados ;
    }
    /**
     * Get the "empleadosIdempleados" field value
     * This field is mapped on the database column "EMPLEADOS_idEMPLEADOS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getEmpleadosIdempleados()
    {
        return this.empleadosIdempleados;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(planillasIdplanillas);
        sb.append("|");
        sb.append(empleadosIdempleados);
        return sb.toString(); 
    } 


}
