/*
 * Java bean class for entity table planillas 
 * Created on 28 oct 2015 ( Date ISO 2015-10-28 - Time 21:52:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "planillas"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Planillas implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idplanillas  ; // Primary Key

    private Date       fecha        ;
    private String     observaciones ;
    private Integer    idPuestoTrabajo ;
    private Integer    idDetalle    ;
    private Integer    idEstado     ;
    private Integer    idTipoFecha  ;
    private Integer    idVolumenEspecial ;

    /**
     * Default constructor
     */
    public Planillas()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idplanillas" field value
     * This field is mapped on the database column "idPLANILLAS" ( type "INT", NotNull : true ) 
     * @param idplanillas
     */
	public void setIdplanillas( Integer idplanillas )
    {
        this.idplanillas = idplanillas ;
    }
    /**
     * Get the "idplanillas" field value
     * This field is mapped on the database column "idPLANILLAS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdplanillas()
    {
        return this.idplanillas;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : FECHA ( DATE ) 
    /**
     * Set the "fecha" field value
     * This field is mapped on the database column "FECHA" ( type "DATE", NotNull : true ) 
     * @param fecha
     */
    public void setFecha( Date fecha )
    {
        this.fecha = fecha;
    }
    /**
     * Get the "fecha" field value
     * This field is mapped on the database column "FECHA" ( type "DATE", NotNull : true ) 
     * @return the field value
     */
    public Date getFecha()
    {
        return this.fecha;
    }

    //--- DATABASE MAPPING : OBSERVACIONES ( VARCHAR ) 
    /**
     * Set the "observaciones" field value
     * This field is mapped on the database column "OBSERVACIONES" ( type "VARCHAR", NotNull : false ) 
     * @param observaciones
     */
    public void setObservaciones( String observaciones )
    {
        this.observaciones = observaciones;
    }
    /**
     * Get the "observaciones" field value
     * This field is mapped on the database column "OBSERVACIONES" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getObservaciones()
    {
        return this.observaciones;
    }

    //--- DATABASE MAPPING : ID_PUESTO_TRABAJO ( INT ) 
    /**
     * Set the "idPuestoTrabajo" field value
     * This field is mapped on the database column "ID_PUESTO_TRABAJO" ( type "INT", NotNull : true ) 
     * @param idPuestoTrabajo
     */
    public void setIdPuestoTrabajo( Integer idPuestoTrabajo )
    {
        this.idPuestoTrabajo = idPuestoTrabajo;
    }
    /**
     * Get the "idPuestoTrabajo" field value
     * This field is mapped on the database column "ID_PUESTO_TRABAJO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getIdPuestoTrabajo()
    {
        return this.idPuestoTrabajo;
    }

    //--- DATABASE MAPPING : ID_DETALLE ( INT ) 
    /**
     * Set the "idDetalle" field value
     * This field is mapped on the database column "ID_DETALLE" ( type "INT", NotNull : true ) 
     * @param idDetalle
     */
    public void setIdDetalle( Integer idDetalle )
    {
        this.idDetalle = idDetalle;
    }
    /**
     * Get the "idDetalle" field value
     * This field is mapped on the database column "ID_DETALLE" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getIdDetalle()
    {
        return this.idDetalle;
    }

    //--- DATABASE MAPPING : ID_ESTADO ( INT ) 
    /**
     * Set the "idEstado" field value
     * This field is mapped on the database column "ID_ESTADO" ( type "INT", NotNull : true ) 
     * @param idEstado
     */
    public void setIdEstado( Integer idEstado )
    {
        this.idEstado = idEstado;
    }
    /**
     * Get the "idEstado" field value
     * This field is mapped on the database column "ID_ESTADO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getIdEstado()
    {
        return this.idEstado;
    }

    //--- DATABASE MAPPING : ID_TIPO_FECHA ( INT ) 
    /**
     * Set the "idTipoFecha" field value
     * This field is mapped on the database column "ID_TIPO_FECHA" ( type "INT", NotNull : true ) 
     * @param idTipoFecha
     */
    public void setIdTipoFecha( Integer idTipoFecha )
    {
        this.idTipoFecha = idTipoFecha;
    }
    /**
     * Get the "idTipoFecha" field value
     * This field is mapped on the database column "ID_TIPO_FECHA" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getIdTipoFecha()
    {
        return this.idTipoFecha;
    }

    //--- DATABASE MAPPING : ID_VOLUMEN_ESPECIAL ( INT ) 
    /**
     * Set the "idVolumenEspecial" field value
     * This field is mapped on the database column "ID_VOLUMEN_ESPECIAL" ( type "INT", NotNull : false ) 
     * @param idVolumenEspecial
     */
    public void setIdVolumenEspecial( Integer idVolumenEspecial )
    {
        this.idVolumenEspecial = idVolumenEspecial;
    }
    /**
     * Get the "idVolumenEspecial" field value
     * This field is mapped on the database column "ID_VOLUMEN_ESPECIAL" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdVolumenEspecial()
    {
        return this.idVolumenEspecial;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idplanillas);
        sb.append("|");
        sb.append(fecha);
        sb.append("|");
        sb.append(observaciones);
        sb.append("|");
        sb.append(idPuestoTrabajo);
        sb.append("|");
        sb.append(idDetalle);
        sb.append("|");
        sb.append(idEstado);
        sb.append("|");
        sb.append(idTipoFecha);
        sb.append("|");
        sb.append(idVolumenEspecial);
        return sb.toString(); 
    } 


}
