/*
 * Java bean class for entity table tipo_fecha 
 * Created on 31 oct 2015 ( Date ISO 2015-10-31 - Time 10:15:17 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;


/**
 * Entity bean for table "tipo_fecha"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TipoFecha implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idtipoFecha  ; // Primary Key

    private String     descripcion  ;

    /**
     * Default constructor
     */
    public TipoFecha()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idtipoFecha" field value
     * This field is mapped on the database column "idTIPO_FECHA" ( type "INT", NotNull : true ) 
     * @param idtipoFecha
     */
	public void setIdtipoFecha( Integer idtipoFecha )
    {
        this.idtipoFecha = idtipoFecha ;
    }
    /**
     * Get the "idtipoFecha" field value
     * This field is mapped on the database column "idTIPO_FECHA" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdtipoFecha()
    {
        return this.idtipoFecha;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DESCRIPCION ( VARCHAR ) 
    /**
     * Set the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : true ) 
     * @param descripcion
     */
    public void setDescripcion( String descripcion )
    {
        this.descripcion = descripcion;
    }
    /**
     * Get the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getDescripcion()
    {
        return this.descripcion;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idtipoFecha);
        sb.append("|");
        sb.append(descripcion);
        return sb.toString(); 
    } 


}
