/*
 * Java bean class for entity table turnos_de_trabajo_has_detalle_planilla 
 * Created on 31 oct 2015 ( Date ISO 2015-10-31 - Time 10:15:17 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;


/**
 * Entity bean for table "turnos_de_trabajo_has_detalle_planilla"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TurnosDeTrabajoHasDetallePlanilla implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    turnosDeTrabajoIdturnosDeTrabajo ; // Primary Key
    private Integer    detallePlanillaIdDetalle ; // Primary Key


    /**
     * Default constructor
     */
    public TurnosDeTrabajoHasDetallePlanilla()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "turnosDeTrabajoIdturnosDeTrabajo" field value
     * This field is mapped on the database column "TURNOS_DE_TRABAJO_idTURNOS_DE_TRABAJO" ( type "INT", NotNull : true ) 
     * @param turnosDeTrabajoIdturnosDeTrabajo
     */
	public void setTurnosDeTrabajoIdturnosDeTrabajo( Integer turnosDeTrabajoIdturnosDeTrabajo )
    {
        this.turnosDeTrabajoIdturnosDeTrabajo = turnosDeTrabajoIdturnosDeTrabajo ;
    }
    /**
     * Get the "turnosDeTrabajoIdturnosDeTrabajo" field value
     * This field is mapped on the database column "TURNOS_DE_TRABAJO_idTURNOS_DE_TRABAJO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getTurnosDeTrabajoIdturnosDeTrabajo()
    {
        return this.turnosDeTrabajoIdturnosDeTrabajo;
    }
    /**
     * Set the "detallePlanillaIdDetalle" field value
     * This field is mapped on the database column "DETALLE_PLANILLA_ID_DETALLE" ( type "INT", NotNull : true ) 
     * @param detallePlanillaIdDetalle
     */
	public void setDetallePlanillaIdDetalle( Integer detallePlanillaIdDetalle )
    {
        this.detallePlanillaIdDetalle = detallePlanillaIdDetalle ;
    }
    /**
     * Get the "detallePlanillaIdDetalle" field value
     * This field is mapped on the database column "DETALLE_PLANILLA_ID_DETALLE" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getDetallePlanillaIdDetalle()
    {
        return this.detallePlanillaIdDetalle;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(turnosDeTrabajoIdturnosDeTrabajo);
        sb.append("|");
        sb.append(detallePlanillaIdDetalle);
        return sb.toString(); 
    } 


}
