/*
 * Java bean class for entity table turnos_de_trabajo 
 * Created on 31 oct 2015 ( Date ISO 2015-10-31 - Time 10:15:17 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;


/**
 * Entity bean for table "turnos_de_trabajo"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TurnosDeTrabajo implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idturnosDeTrabajo ; // Primary Key

    private String     nombre       ;
    private String     descripcion  ;
    private Integer    idPuestoTrabajo ;
    private Boolean    turnoRotatorio ;
    private Integer    idSiguienteTurno ;

    /**
     * Default constructor
     */
    public TurnosDeTrabajo()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idturnosDeTrabajo" field value
     * This field is mapped on the database column "idTURNOS_DE_TRABAJO" ( type "INT", NotNull : true ) 
     * @param idturnosDeTrabajo
     */
	public void setIdturnosDeTrabajo( Integer idturnosDeTrabajo )
    {
        this.idturnosDeTrabajo = idturnosDeTrabajo ;
    }
    /**
     * Get the "idturnosDeTrabajo" field value
     * This field is mapped on the database column "idTURNOS_DE_TRABAJO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdturnosDeTrabajo()
    {
        return this.idturnosDeTrabajo;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOMBRE ( VARCHAR ) 
    /**
     * Set the "nombre" field value
     * This field is mapped on the database column "NOMBRE" ( type "VARCHAR", NotNull : true ) 
     * @param nombre
     */
    public void setNombre( String nombre )
    {
        this.nombre = nombre;
    }
    /**
     * Get the "nombre" field value
     * This field is mapped on the database column "NOMBRE" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getNombre()
    {
        return this.nombre;
    }

    //--- DATABASE MAPPING : DESCRIPCION ( VARCHAR ) 
    /**
     * Set the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : false ) 
     * @param descripcion
     */
    public void setDescripcion( String descripcion )
    {
        this.descripcion = descripcion;
    }
    /**
     * Get the "descripcion" field value
     * This field is mapped on the database column "DESCRIPCION" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getDescripcion()
    {
        return this.descripcion;
    }

    //--- DATABASE MAPPING : ID_PUESTO_TRABAJO ( INT ) 
    /**
     * Set the "idPuestoTrabajo" field value
     * This field is mapped on the database column "ID_PUESTO_TRABAJO" ( type "INT", NotNull : true ) 
     * @param idPuestoTrabajo
     */
    public void setIdPuestoTrabajo( Integer idPuestoTrabajo )
    {
        this.idPuestoTrabajo = idPuestoTrabajo;
    }
    /**
     * Get the "idPuestoTrabajo" field value
     * This field is mapped on the database column "ID_PUESTO_TRABAJO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getIdPuestoTrabajo()
    {
        return this.idPuestoTrabajo;
    }

    //--- DATABASE MAPPING : TURNO_ROTATORIO ( BIT ) 
    /**
     * Set the "turnoRotatorio" field value
     * This field is mapped on the database column "TURNO_ROTATORIO" ( type "BIT", NotNull : false ) 
     * @param turnoRotatorio
     */
    public void setTurnoRotatorio( Boolean turnoRotatorio )
    {
        this.turnoRotatorio = turnoRotatorio;
    }
    /**
     * Get the "turnoRotatorio" field value
     * This field is mapped on the database column "TURNO_ROTATORIO" ( type "BIT", NotNull : false ) 
     * @return the field value
     */
    public Boolean getTurnoRotatorio()
    {
        return this.turnoRotatorio;
    }

    //--- DATABASE MAPPING : ID_SIGUIENTE_TURNO ( INT ) 
    /**
     * Set the "idSiguienteTurno" field value
     * This field is mapped on the database column "ID_SIGUIENTE_TURNO" ( type "INT", NotNull : false ) 
     * @param idSiguienteTurno
     */
    public void setIdSiguienteTurno( Integer idSiguienteTurno )
    {
        this.idSiguienteTurno = idSiguienteTurno;
    }
    /**
     * Get the "idSiguienteTurno" field value
     * This field is mapped on the database column "ID_SIGUIENTE_TURNO" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getIdSiguienteTurno()
    {
        return this.idSiguienteTurno;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idturnosDeTrabajo);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(idPuestoTrabajo);
        sb.append("|");
        sb.append(turnoRotatorio);
        sb.append("|");
        sb.append(idSiguienteTurno);
        return sb.toString(); 
    } 


}
