/*
 * Java bean class for entity table vacaciones 
 * Created on 28 oct 2015 ( Date ISO 2015-10-28 - Time 21:52:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package org.sun.resorts.holidays.model;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "vacaciones"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Vacaciones implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    idvacaciones ; // Primary Key

    private String     observaciones ;
    private Date       fechaVacaciones ;
    private Integer    empleadosIdempleados ;
    private Integer    estado       ;
    private Boolean    festivoPendiente ;

    /**
     * Default constructor
     */
    public Vacaciones()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idvacaciones" field value
     * This field is mapped on the database column "idVACACIONES" ( type "INT", NotNull : true ) 
     * @param idvacaciones
     */
	public void setIdvacaciones( Integer idvacaciones )
    {
        this.idvacaciones = idvacaciones ;
    }
    /**
     * Get the "idvacaciones" field value
     * This field is mapped on the database column "idVACACIONES" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdvacaciones()
    {
        return this.idvacaciones;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : OBSERVACIONES ( VARCHAR ) 
    /**
     * Set the "observaciones" field value
     * This field is mapped on the database column "OBSERVACIONES" ( type "VARCHAR", NotNull : true ) 
     * @param observaciones
     */
    public void setObservaciones( String observaciones )
    {
        this.observaciones = observaciones;
    }
    /**
     * Get the "observaciones" field value
     * This field is mapped on the database column "OBSERVACIONES" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getObservaciones()
    {
        return this.observaciones;
    }

    //--- DATABASE MAPPING : FECHA_VACACIONES ( DATE ) 
    /**
     * Set the "fechaVacaciones" field value
     * This field is mapped on the database column "FECHA_VACACIONES" ( type "DATE", NotNull : true ) 
     * @param fechaVacaciones
     */
    public void setFechaVacaciones( Date fechaVacaciones )
    {
        this.fechaVacaciones = fechaVacaciones;
    }
    /**
     * Get the "fechaVacaciones" field value
     * This field is mapped on the database column "FECHA_VACACIONES" ( type "DATE", NotNull : true ) 
     * @return the field value
     */
    public Date getFechaVacaciones()
    {
        return this.fechaVacaciones;
    }

    //--- DATABASE MAPPING : EMPLEADOS_idEMPLEADOS ( INT ) 
    /**
     * Set the "empleadosIdempleados" field value
     * This field is mapped on the database column "EMPLEADOS_idEMPLEADOS" ( type "INT", NotNull : true ) 
     * @param empleadosIdempleados
     */
    public void setEmpleadosIdempleados( Integer empleadosIdempleados )
    {
        this.empleadosIdempleados = empleadosIdempleados;
    }
    /**
     * Get the "empleadosIdempleados" field value
     * This field is mapped on the database column "EMPLEADOS_idEMPLEADOS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getEmpleadosIdempleados()
    {
        return this.empleadosIdempleados;
    }

    //--- DATABASE MAPPING : ESTADO ( INT ) 
    /**
     * Set the "estado" field value
     * This field is mapped on the database column "ESTADO" ( type "INT", NotNull : true ) 
     * @param estado
     */
    public void setEstado( Integer estado )
    {
        this.estado = estado;
    }
    /**
     * Get the "estado" field value
     * This field is mapped on the database column "ESTADO" ( type "INT", NotNull : true ) 
     * @return the field value
     */
    public Integer getEstado()
    {
        return this.estado;
    }

    //--- DATABASE MAPPING : FESTIVO_PENDIENTE ( BIT ) 
    /**
     * Set the "festivoPendiente" field value
     * This field is mapped on the database column "FESTIVO_PENDIENTE" ( type "BIT", NotNull : true ) 
     * @param festivoPendiente
     */
    public void setFestivoPendiente( Boolean festivoPendiente )
    {
        this.festivoPendiente = festivoPendiente;
    }
    /**
     * Get the "festivoPendiente" field value
     * This field is mapped on the database column "FESTIVO_PENDIENTE" ( type "BIT", NotNull : true ) 
     * @return the field value
     */
    public Boolean getFestivoPendiente()
    {
        return this.festivoPendiente;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idvacaciones);
        sb.append("|");
        sb.append(observaciones);
        sb.append("|");
        sb.append(fechaVacaciones);
        sb.append("|");
        sb.append(empleadosIdempleados);
        sb.append("|");
        sb.append(estado);
        sb.append("|");
        sb.append(festivoPendiente);
        return sb.toString(); 
    } 


}
