/*
 * Created on 28 oct 2015 ( Time 21:40:09 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service;

import java.util.List;

import org.sun.resorts.holidays.model.Direccion;

/**
 * Business Service Interface for entity Direccion.
 */
public interface DireccionService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param iddireccion
	 * @return entity
	 */
	Direccion findById( Integer iddireccion  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Direccion> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Direccion save(Direccion entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Direccion update(Direccion entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Direccion create(Direccion entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param iddireccion
	 */
	void delete( Integer iddireccion );


}
