/*
 * Created on 28 oct 2015 ( Time 21:40:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service;

import java.util.List;

import org.sun.resorts.holidays.model.Planillas;

/**
 * Business Service Interface for entity Planillas.
 */
public interface PlanillasService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idplanillas
	 * @return entity
	 */
	Planillas findById( Integer idplanillas  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Planillas> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Planillas save(Planillas entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Planillas update(Planillas entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Planillas create(Planillas entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idplanillas
	 */
	void delete( Integer idplanillas );


}
