/*
 * Created on 28 oct 2015 ( Time 21:40:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service;

import java.util.List;

import org.sun.resorts.holidays.model.PlanillasHasEmpleados;

/**
 * Business Service Interface for entity PlanillasHasEmpleados.
 */
public interface PlanillasHasEmpleadosService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param planillasIdplanillas
	 * @param empleadosIdempleados
	 * @return entity
	 */
	PlanillasHasEmpleados findById( Integer planillasIdplanillas, Integer empleadosIdempleados  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<PlanillasHasEmpleados> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	PlanillasHasEmpleados save(PlanillasHasEmpleados entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	PlanillasHasEmpleados update(PlanillasHasEmpleados entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	PlanillasHasEmpleados create(PlanillasHasEmpleados entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param planillasIdplanillas
	 * @param empleadosIdempleados
	 */
	void delete( Integer planillasIdplanillas, Integer empleadosIdempleados );


}
