/*
 * Created on 28 oct 2015 ( Time 21:40:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service;

import java.util.List;

import org.sun.resorts.holidays.model.TipoFecha;

/**
 * Business Service Interface for entity TipoFecha.
 */
public interface TipoFechaService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idtipoFecha
	 * @return entity
	 */
	TipoFecha findById( Integer idtipoFecha  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TipoFecha> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TipoFecha save(TipoFecha entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipoFecha update(TipoFecha entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipoFecha create(TipoFecha entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idtipoFecha
	 */
	void delete( Integer idtipoFecha );


}
