/*
 * Created on 28 oct 2015 ( Time 21:40:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service;

import java.util.List;

import org.sun.resorts.holidays.model.TurnosDeTrabajo;

/**
 * Business Service Interface for entity TurnosDeTrabajo.
 */
public interface TurnosDeTrabajoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idturnosDeTrabajo
	 * @return entity
	 */
	TurnosDeTrabajo findById( Integer idturnosDeTrabajo  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TurnosDeTrabajo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TurnosDeTrabajo save(TurnosDeTrabajo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TurnosDeTrabajo update(TurnosDeTrabajo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TurnosDeTrabajo create(TurnosDeTrabajo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idturnosDeTrabajo
	 */
	void delete( Integer idturnosDeTrabajo );


}
