/*
 * Created on 28 oct 2015 ( Time 21:40:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.sun.resorts.holidays.business.service;

import java.util.List;

import org.sun.resorts.holidays.model.TurnosTrabajoEspeciales;

/**
 * Business Service Interface for entity TurnosTrabajoEspeciales.
 */
public interface TurnosTrabajoEspecialesService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param empleadosIdempleados
	 * @param turnosDeTrabajoIdturnosDeTrabajo
	 * @return entity
	 */
	TurnosTrabajoEspeciales findById( Integer empleadosIdempleados, Integer turnosDeTrabajoIdturnosDeTrabajo  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TurnosTrabajoEspeciales> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TurnosTrabajoEspeciales save(TurnosTrabajoEspeciales entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TurnosTrabajoEspeciales update(TurnosTrabajoEspeciales entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TurnosTrabajoEspeciales create(TurnosTrabajoEspeciales entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param empleadosIdempleados
	 * @param turnosDeTrabajoIdturnosDeTrabajo
	 */
	void delete( Integer empleadosIdempleados, Integer turnosDeTrabajoIdturnosDeTrabajo );


}
